### ISSUE TITLE
Plotch (Buyer App) - Compliance Check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#153]
**search_full_catalog_refresh**

- /message/intent/fulfillment/end/location must have required property 'address'

**search_inc_refresh**

- context/city should be "\*" while sending search_inc_catalog request
- /message/intent/tags/list/end_time/value cannot be greater than /context/timestamp

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/@ondc/org/fssai_license_no must NOT have fewer than 14 characters
- /message/catalog/bpp/providers/items/quantity/available/count must be equal to one of the allowed values (99,0)
- invalid value passed in api _id: 33992
- /message/catalog/bpp~1providers/0/items/0/tags must be array
- Either one of fixed timings (range) or split timings (both frequency and times) should be provided in /bpp/providers[0]/locations/time
- 'time_to' must be greater than 'time_from' passed in tags
- serviceability construct /bpp/providers[0]/tags[0] should be defined as per the API contract

**select**

- /message/order/items/id in item: 2455688 should be one of the /item/id mapped in on_search

**init**

- value of address.name, address.building and address.locality should be unique
- items[0].fulfillment_id mismatches for Item 2455688 in /on_select and /init

**on_init**

- /message/order must have required property 'tags'/message/order must have required property 'tags'

**on_status**

- /message/order/fulfillments/0/start/location must have required property 'address'

**common**

- City code mismatch in /search and other api calls

@dileswarpatnaik

**Comment by sharmasahil0331** [comment]
**search_full_catalog_refresh**

- /message/intent/fulfillment/end/location must have required property 'address'
- /context/city should be as per the provided gps in /message/intent/fulfillment/end/location

**select**

- Timestamp for /on_search api cannot be greater than or equal to /select api
- /message/order/provider/location/id should be one of the location/id provided in on_search_full_catalog_refresh
- context/city should match context/city provided in search_full_catalog_refresh

**init**

- address.building should be more than 3 chars
- value of address.name, address.building and address.locality should be unique
- items[0].fulfillment_id mismatches for Item 1119813075 in /on_select and /init
- fulfillment id F1 does not exist in /on_select

**confirm**

- City code mismatch in /search and /confirm
- billing issues
    -  Key 'updated_at' mismatch: 2023-12-06T07:59:44.506Z !== 2023-12-06T08:00:01.843Z
    - Key 'created_at' mismatch: 2023-12-06T07:59:44.506Z !== 2023-12-06T08:00:01.843Z
    
@dileswarpatnaik

**Comment by dileswarp** [comment]
As per document 

- /message/intent/fulfillment/end/location must have required property 'address' is Optional. 
- context/city should match context/city provided in search_full_catalog_refresh : Already we are using same city only.
- fulfillment id F1 does not exist in /on_select fullfillment block F1 is there.
Please review and share your feedback asap  https://github.com/ONDC-Official/v1.2.0-logs/pull/305
@sahil-ondc @bluecypher

**Comment by BLR-0118** [comment]
Flow 1
====
Full catalog refresh:
1. /search:
- pls remove bap_terms from /search (full, incremental) until static terms are enabled;
- pls share search by city log as well;
2. /on_search:
- "Women's Indian & Fusion Wear" is not a valid category as per list [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0);
- what does hyperlocal serviceability (type - "10") mean when most buyer apps cap at 5km; if this is pan-India, why not use type "12"?
- why are fashion items ("Women's Indian & Fusion Wear" category) being included in F&B catalog (RET-11)?
- default value for item available/max qty is "99" and if there's a cap per order, the max qty reflects it; what does value of "100", "10", etc mean?
- choco chips (1119814462) is not really "Cakes" and there are other items like this; why not use category "F&B" for all F&B items?
- custom menu has been defined but no items are assigned to it using category_ids. Why?
- need test case for customizations where base item price is 0 & customizations have non-zero price (as explained [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795));

Incremental catalog refresh:
1. Full catalog /search has BFF as 3% but it becomes 0% in incremental search request. What does this mean?
2. Incremental catalog pull (with both start & end time) requires solicited response (same transaction_id & message_id for request & response), which isn't happening here;
3. Isn't incremental push supported along with other use cases - provider / location disable, location close & reopen? 
4. Incremental response is invalid (as there is no custom group defined in full pull; if the intent is to change an item from customizable to non-customizable, you should disable the customizable item & create a new non-customizable item;

Flow 2
====
1. /select:
- dynamic item id (item.parent_item_id) is created by the buyer app to identify customized product (i.e. item + customizations); in this case, you can't use the item id from the catalog (1119813075);
- not clear what's being selected here - 2 cakes with sprinklers or 1 cake + 1 cake with sprinkler as both options possible since customization group is optional (min - 0). For either of these options, there should be 2 different dynamic items created & sent in /select;
2. /on_init:
- remove everything from bap_terms & bpp_terms except tax numbers, cancellation terms (these will be enabled in phase 2);
- remove provider_location;
3. /confirm:
- payment.status is paid but payment.params.transaction_id is missing;
- also all payment.params values are missing from /on_status - this can't happen if there's a single order object which maintains the current state;
4. /on_status:
- fulfillment.tags.tracking.gps_enabled may be used to indicate gps coordinates have been enabled for tracking to optimize the no of /track requests;

Flow 3 - needs to cover the out-of-stock scenarios;
Flow 4 & 5 are also required;

Test scenarios are [here](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795)

**Comment by BLR-0118** [comment]
@dileswarp

**Comment by dileswarp** [comment]
@BLR-0118 Sir , As per feedback , shared the updated logs , Please review https://github.com/ONDC-Official/v1.2.0-logs/pull/449

**Comment by BLR-0118** [comment]
all plotch issues being tracked in #950
