### ISSUE TITLE
Gupshup IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#1818]
"issue
     "schemaErr0": "/message/issue/description/images/0 must be string"
       on_issue"
     "created_at": "'created_at' should match issue's 'created_at'"
       on_issue_status": {
      "created_at": "'created_at' should match issue's 'created_at'"

Flow 1 _ issue related with an item is missing .

Please submit logs once verified with Utility

@anilSinghgupshup

**Comment by RupalSingla** [comment]
Issue 1 
issue_status , on_issue__status and issue close are missing

Issue 2
issue_status , on_issue__status and issue close are missing

@anilSinghgupshup

**Comment by anilSinghgupshup** [comment]
@RupalSingla : As per our understanding.. we have shared the comments.. If there is any descripancy in the understanding we can connect over call to understand it so that when we submit logs next time.. there will not be any issue in the logs.

Issue 1
issue_status , on_issue__status and issue close are missing.
**Gupshup Comment : Already present in the submitted logs**
Issue 2
issue_status , on_issue__status and issue close are missing 
**Gupshup Comment : Already present in the submitted logs**

Issue 3

in_issue_closer is not requried. 
**Gupshup Comment : We can ignore/ we will remove in next logs**
transaction id of on_issee and issue status are different
**Gupshup Comment : We fixed this issue. It will not present in next logs**
respondat_action are have different timestap in updated_at in processing action
**Gupshup Comment : This issue is coming from the event from ONDC**
resolution provider action - processing and resolved are have a timestap error of 1 year.
**Gupshup Comment : This issue is coming from the event from ONDC**

IGM is a single flow only. Do you mean to submit logs for item and delivery issues in separate folder.

**Comment by anilSinghgupshup** [comment]
@RupalSingla : We have pushed updated logs in the followings pull request:
https://github.com/ONDC-Official/v1.2.0-logs/pull/1878

**Comment by RupalSingla** [comment]
Flow 1 :
Delivery 
 on_issue_status 
Repondant action needs to have action - Resolved before closing the issue .

ITem missing
 on_issue_status 
Repondant action needs to have action - Resolved before closing the issue .
@anilSinghgupshup

**Comment by RupalSingla** [comment]
Logs  cleared for version 1.0.0 @anilSinghgupshup
