### ISSUE TITLE
MedPay (H&W) - compliance checks

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#183]
**on_search_full_catalog_refresh**

- /message/catalog/bpp~1providers/0/items/0/quantity/available/count must be equal to one of the allowed values (99,0)
- duplicate item id: 331545 in bpp/providers[0]
- invalid area_code as per the gps passed in /message/catalog/bpp/providers/locations

**search_inc_refresh**

- /context must have required property 'ttl'

**on_select**

- invalid context/city as per the store location
- Quote breakup Payment title "Packaging charges" is not as per the API Contract

**on_confirm**

- /message/order/payment/@ondc/org/settlement_details/0 must have required property 'beneficiary_name'

@medpay-vishal-kumar

**Comment by sharmasahil0331** [comment]
**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/items/quantity/maximum/count must be equal to one of the allowed values (99,0)

**search_inc_catalog_refresh**

- invalid key 'fulfillment' provided in /message/intent

**on_search_inc_catalog_refresh**

- provider id: 1001-3716-9032-6275 in bpp/providers didn't matched for providers id of /on_search_full_catalog_refresh

**select**

- Timestamp for /on_search api cannot be greater than or equal to /select api

**on_select**

- /message/order/quote/breakup/item/quantity/maximum/count must be equal to one of the allowed values (99,0)

**on_init**

- invalid key 'quantity' provided in /message/order/quote/breakup/item

**on_confirm**

- invalid key 'quantity' provided in /message/order/quote/breakup/item

@medpay-vishal-kumar

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- pls use this [list](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1999500764) for category, (required) attributes (in addition to what has been defined);
2. incremental refresh:
- is incremental push supported?

Flow 2
====
1. /on_init:
- remove provider_location;
- except tax_number, remove everything else in bpp_terms as this hasn't been enabled yet;
2. /on_status:
- fulfillment.tags.tracking.gps_enabled may be used to indicate gps coordinates have been enabled for tracking to optimize the no of /track requests;

Flow 3
====
1. /on_select (out_of_stock):
- pls use the updated error.message format for item(s) out of stock as noted [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl);

Flow 4 & 5
=======
- Cancel & RTO flows are incorrect - every cancel request creates a separate fulfillment of type "Cancel" or "RTO" and items assigned to forward shipment fulfillment are zero'd out & new entries created for items to be assigned to the Cancel / RTO fulfillment. Each such fulfillment will also have a quote trail to keep track of the reduction in order value (and hence refund) due to the cancellation / RTO. Check the details [here](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit)

**Comment by BLR-0118** [comment]
pls resubmit logs only for issues mentioned above
@medpay-vishal-kumar

**Comment by medpay-vishal-kumar** [comment]
@BLR-0118 Thank you for the feedback.

## Flow 1
2. We support 1 time incremental push.

**Comment by medpay-vishal-kumar** [comment]
Have raised PR for related flows only. Please check @BLR-0118

**Comment by medpay-vishal-kumar** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/412

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- item unitized qty for "shampoo" etc. => shouldn't this be in millilitre or litre instead of "unit"?
- item.descriptor.code => isn't there an EAN type of identifier? what does code "5" refer to?
- item.quantity.maximum.count of 20 means "max 20 per order"?

No incremental catalog update?

Flow 2
====
1. /on_track:
- tracking.location.updated_at is when the gps coordinates are updated in the system; hence, this must be >= tracking.location.time.timestamp (which identifies the as of time for the gps coordinates)

remaining flows ok;
pls resubmit logs only for the above issues

**Comment by BLR-0118** [comment]
@medpay-vishal-kumar

**Comment by medpay-vishal-kumar** [comment]
@BLR-0118 Thanks for the feedback.

## Flow 1
1. /on_search
- We will change this to show the actual unit in case of Shampoo and other products. In case of tablet and capsules, what do you suggest we should do as in one unit it can be, there are 1 pack of 10 strips or 5 pack of 10 strips?
- 5 refers to others. As we are using 5:<sku_id> as code. We do not have EAN.
- Yes, max 20 is allowed.

We had the incremental catalog update in older version. Since there was not issue related to that, we didn't put that in the latest submission. Please let me know if we need to put it. I will resubmit that again.

## FLow 2
1. Will fix this. 

Please suggest on **Flow 1**. So that we can submit the logs again. Thank you!

**Comment by BLR-0118** [comment]
1. /on_search:
- for tablets & capsules, a unit would be a pack; hence:
- 1 pack, 10 strips: can be "1" unit, with "10 strips per pack" in the product name / short desc;
- 5 packs, 10 strips each: can be "5" unit, with "10 strips per pack" in the product name / short desc;
- what do you think?

2. Incremental updates:
- are you supporting both: pull (1-time), push (regular)?
- all buyer apps will support both modes, with push (regular) being frequently used;
- just curious: what item attributes will change frequently for "Health & Wellness" category?

**Comment by BLR-0118** [comment]
@amit-gupta-medpay @medpay-vishal-kumar

**Comment by medpay-vishal-kumar** [comment]
@BLR-0118 @amit-gupta-medpay

1. /on_search
- For tab and cap, it makes sense. Will do that.

2. Incremental updates:
- We are only supporting only pull (1 time)
- We can add support for incremental-push, but since nothing really changes frequently which needs to be communicated with buyer app in real time.
- Changes can be packaging and price updates but those does not changes frequently. Which is why we are only going with incremental pull(1-time).

But we can support incremental push (regular). if needed.

Shall we submit the incremental-pull log again?

**Comment by BLR-0118** [comment]
No need to resubmit incremental pull logs as I've verified it.
I'm clearing your logs. Pls make sure the above changes have been made.

**Comment by BLR-0118** [comment]
@medpay-vishal-kumar

**Comment by medpay-vishal-kumar** [comment]
@BLR-0118 Noted. Thank you!
