### ISSUE TITLE
NDHGO (SA : RET12) - Compliance Check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2052]
# **NDHGO RET12**
#### On_search

- If `month_year_of_manufacture_packing_import` is not available, please provide `NA` and not an empty string.
- Invalid attribute `@ondc/org/statutory_reqs_prepackaged_food` for `ret12` domain.
- If `"brand_owner_FSSAI_license_no": "Refer Product Image"`, then the image URL should also be accessible along with the details. If you want to use the back image, then `tags.back_image` is mandatory with the required details.
- Image URL should be accessible.
- For attribute `size_chart`, please provide URL.
- `"@ondc/org/time_to_ship": “P7DT0H0M0S”` should be just `"P7D"`.

#### On_search_inc
- Same as above.

@rajib-senrysa

**Comment by rajib-senrysa** [comment]
@Jagannath-wits 

> Timing object not captured properly. Please refer to contract, and timing should be provided for all fulfillments and orders. If the timing is the same for all, you can create a single timing object with type All.

This is what we have already done. Can you please clarify what is wrong with the following JSON?

```json
{
  "list": [
      {
          "code": "type",
          "value": "All"
      },
      {
          "code": "location",
          "value": "L-134963"
      },
      {
          "code": "day_from",
          "value": "1"
      },
      {
          "code": "day_to",
          "value": "7"
      },
      {
          "code": "time_from",
          "value": "0000"
      },
      {
          "code": "time_to",
          "value": "2359"
      }
  ],
  "code": "timing"
},
```

**Comment by rajib-senrysa** [comment]
@Jagannath-wits 

> Image URL should be accessible.

Can you kindly clarify which image isn't accessible?

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits
> 
> > Timing object not captured properly. Please refer to contract, and timing should be provided for all fulfillments and orders. If the timing is the same for all, you can create a single timing object with type All.
> 
> This is what we have already done. Can you please clarify what is wrong with the following JSON?
> 
> ```json
> {
>   "list": [
>       {
>           "code": "type",
>           "value": "All"
>       },
>       {
>           "code": "location",
>           "value": "L-134963"
>       },
>       {
>           "code": "day_from",
>           "value": "1"
>       },
>       {
>           "code": "day_to",
>           "value": "7"
>       },
>       {
>           "code": "time_from",
>           "value": "0000"
>       },
>       {
>           "code": "time_to",
>           "value": "2359"
>       }
>   ],
>   "code": "timing"
> },
> ```

This is correct

**Comment by Jagannath-wits** [comment]
> @Jagannath-wits
> 
> > Image URL should be accessible.
> 
> Can you kindly clarify which image isn't accessible?

- https://ndhcustomerdocumentsbucket.s3.ap-south-1.amazonaws.com/ndh-assets/img/no_image.png

**Comment by rajib-senrysa** [comment]
> > @Jagannath-wits
> > > Image URL should be accessible.
> > 
> > 
> > Can you kindly clarify which image isn't accessible?
> 
> - https://ndhcustomerdocumentsbucket.s3.ap-south-1.amazonaws.com/ndh-assets/img/no_image.png

@Jagannath-wits That is a valid Image. We have a placeholder image when there aren't any product images available. The link isn't broken. This is the actual image. We have done this so that there is at least one valid image per product.

![image](https://github.com/user-attachments/assets/d14f312a-3898-477c-b247-0399acf61129)

**Comment by Jagannath-wits** [comment]
> > > @Jagannath-wits
> > > > Image URL should be accessible.
> > > 
> > > 
> > > Can you kindly clarify which image isn't accessible?
> > 
> > 
> > - https://ndhcustomerdocumentsbucket.s3.ap-south-1.amazonaws.com/ndh-assets/img/no_image.png
> 
> @Jagannath-wits That is a valid Image. We have a placeholder image when there aren't any product images available. The link isn't broken. This is the actual image. We have done this so that there is at least one valid image per product / category.
> 
> ![image](https://private-user-images.githubusercontent.com/147053728/348624764-d14f312a-3898-477c-b247-0399acf61129.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMzAzMzksIm5iZiI6MTcyMTAzMDAzOSwicGF0aCI6Ii8xNDcwNTM3MjgvMzQ4NjI0NzY0LWQxNGYzMTJhLTM4OTgtNDc3Yy1iMjQ3LTAzOTlhY2Y2MTEyOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQwNzUzNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzQ2NTc3OTU2N2RiZWYwNjJiODVkZjhhYzhiY2Q1YzllODkxNGYwMmJiNGJhNDNmNTJkNTFkNGJjMWU5ZTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ba_LT37Fj9NT3ALZOofoWqUtRUIM0CTAOAe8tVYf4Os)

Ok, please proceed with other fixes

**Comment by rajib-senrysa** [comment]
@Jagannath-wits We have resubmitted the revised logs. Kindly merge and review!

**Comment by rajib-senrysa** [comment]
@Jagannath-wits We have resubmitted the revised logs. Kindly merge and review!

**Comment by bmonish** [comment]
@Jagannath-wits We have resubmitted the revised logs. Kindly merge and review!

**Comment by rajib-senrysa** [comment]
@Jagannath-wits @sandeepshahi Any update?

**Comment by Jagannath-wits** [comment]
### On Search

- Radius can’t be 3000km; kindly provide a valid range between 50-500 even if the serviceability is PAN India.
- Days can’t be like this: `‘5,1,7,2,6,4,3’` and should be in sequence.
- `imported_product_country_of_origin` is not required in `@ondc/org/statutory_reqs_packaged_commodities`.

**Comment by bmonish** [comment]
@Jagannath-wits Submitted the revised logs. Kindly merge and review.

**Comment by sahil-ondc** [comment]
## Flow 1

### On Search
- If the fulfillments are not provided in the bpp/providers/fulfillments, It should not be present in the bpp/fulfillments
- ‘net_quantity_or_measure_of_commodity_in_pkg’ is not required in ‘@ondc/org/statutory_reqs_packaged_commodities’ 

### On Search Inc
- No Incremental changes are observed for the following item_id : ‘MTM0OTYzXzY2ODY1NTdmNGI5YTZmMjQ5MzNhNzNjMV8zX1A=‘

## Flow 6

### Select
- Invalid item_id: ‘MTM0OTYzXzY2ODY0MGFhMjEyNWU1NzhhNDY2ZmM4OF8zX1A=‘ which is not present in on_search

### On Select
- context/timestamp difference between /on_select and /select should be less than 5 sec
- ‘P7DT0H0M0S’, If the TAT is 7D, kindly provide P7D
- Quoted Price in /on_select INR 2854 does not match with the total price of items in /select INR 1856 i.e price for the item mismatch in on_search and on_select due to invalid items which is not present in on_search : ‘MTM0OTYzXzY2ODY0MGFhMjEyNWU1NzhhNDY2ZmM4OF8zX1A=‘

### On Init
- context/timestamp difference between /on_init and /init should be less than 5 sec

### On Confirm
- "tags": [] can’t be empty like this in the quote.breakup

### On Status Picked, On Status Out For Delivery, On Status Delivered
- Invoice should be publically accessible 
- tracking url is not accessible 

@bmonish

**Comment by rajib-senrysa** [comment]
@sahil-ondc Kindly review the updated logs

**Comment by sahil-ondc** [comment]
## Flow 1
### On Search
- ‘ttl’  is not required in ‘on_search’
- If the fulfillments are not provided in the bpp/providers/fulfillments should not be present in the bpp/fulfillments
 
## Flow 6
### On Select
- There is a price mismatch for the item_id : ‘MTM0OTYzXzY2ODY1NTdmNGI5YTZmMjQ5MzNhNzNjMV8zX1A=‘ as compared to the on_search action call
 
 
### On Update Part Cancel
- tags are not required in the items for the item_id : ‘MTM0OTYzXzY2YjQ1NjI2Y2ZhYjc1NzliOTBhNjQ3YV8zX1A=‘ if the type is ‘item’
 
 
### On Status Picked
- invoice is not updated after the part cancellation
- tracking url is not accessible

@rajib-senrysa

**Comment by bmonish** [comment]
@sahil-ondc 

> ‘ttl’ is not required in ‘on_search’

It's present in the contract, right? (Refer Page No. 46)

----

> If the fulfillments are not provided in the bpp/providers/fulfillments should not be present in the bpp/fulfillments

Please check this comment by Supriyo. We are sending the `bpp/fulfillments` as the superset of all the fulfillment types we support.
https://github.com/ONDC-Official/v1.2.0-logs/issues/2068#issuecomment-2298095126

---

> There is a price mismatch for the item_id : ‘MTM0OTYzXzY2ODY1NTdmNGI5YTZmMjQ5MzNhNzNjMV8zX1A=‘ as compared to the on_search action call

Because it was updated in the inc-on_search. And the price you see in the on_select is the updated price.
```json
"id": "MTM0OTYzXzY2ODY1NTdmNGI5YTZmMjQ5MzNhNzNjMV8zX1A=",
"price": {
  "currency": "INR",
  "value": "346.00",
  "maximum_value": "549.00"
}
```

---

> invoice is not updated after the part cancellation

Is it mandatory for the invoice to be updated?

**Comment by bmonish** [comment]
@BLR-0118 @sandeepshahi @sahil-ondc Kindly clarify these issues please.

**Comment by BLR-0118** [comment]
log cleared for v1.2.0
