### ISSUE TITLE
Wemotive - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#2085]
Multiple issues identified. Please use the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) and self rectify the issues and submit again.

@wemakshaychavan

**Comment by abhinavv245** [comment]
**/search**

- payment/type 'ON-ORDER' and 'ON-FULFILLMENT' are currently not enabled, please use 'POST-FULFILLMENT'

**/init**

- please avoid dummy data, provide correct address and contact details

**/on_update**

- /on_update/0/message/order/fulfillments/0/tracking must be equal to constant (true)",

**/on_status**

- In case of RTO, fulfillment with type 'Delivery/Prepaid' needs to in 'Cancelled' state"
- tracking tag to be provided in fulfillments/tags

**/on_cancel**

- /on_cancel/0/message/order must have required property 'created_at

## TAT Breach

**/confirm**

- payload is missing

Note: Flow with ready to ship at confirm to be implemented as well

@wemakshaychavan

**Comment by BLR-0118** [comment]
RTS flow:
1. /confirm:
- where's bpp_terms & bap_terms coming from? no static terms / cancellation terms defined by LSP;
2. /track:
- why is this having earlier timestamp than /update (when RTS is enabled)?
3. how will anyone use this LBNP - curious because the retail order no & logistics order no are same;

**Comment by BLR-0118** [comment]
@wemakshaychavan

**Comment by wemakshaychavan** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/2235

/confirm:
where's bpp_terms & bap_terms coming from? no static terms / cancellation terms defined by LSP;  -> **fixed , we will send bpp/terms only if we receive it in on_init**
/track:
why is this having earlier timestamp than /update (when RTS is enabled)? **Fixed** 
are you supporting hyperlocal / intercity logistics? **Only hyperlocal with immediate delivery** 
are you supporting other pickup / delivery codes like OTP? **No we are not supporting OTP as of now**
how will anyone use this LBNP - curious because the retail order no & logistics order no are same; **We had kept same orderId as of retails for LSP. In recent pull request we have kept it separate.** 

@BLR-0118

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0;
