### ISSUE TITLE
BuyNxt (SA : RET16) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2096]
### Flow 1 - /on_search
- Entire address need not be provided in `/locations/address/street`.

### Flow 2 - /on_confirm
- How can estimated pickup and delivery time ranges be provided even before the order is accepted?  
- Considering that the 'time_to_ship' provided in `/on_search` is 3 hours, how can the estimated pickup time range be only 1 hour?

### /on_status (picked)
- How can actual pickup timestamp be earlier than timestamp in "Packed" state?

### Flow 4 - /on_cancel
- Updated_at timestamp is not captured correctly for order and precancel state.

### Flow 5 - /on_cancel
- Actual pickup timestamp is missing from cancelled forward shipment.
- "005" is not a valid RTO reason ID.
- Quote_trail should only include line items with delta changes; delivery with value = 0 should not be provided in quote_trail.
- No need to add RTO delivery charges in quote/breakup if value = 0.

### /on_status (RTO)
- Similar issues as above.
- Why has the RTO fulfillment ID changed in items object?
- Tags/cancel_request need not be provided in RTO fulfillment.

### Flow 6 - /on_update (part cancel)
- Why are the cancellation fulfillment IDs the same for both partial and full cancellations?
- What happens if a full cancellation is initiated by BNP after a partial cancellation is received from SNP?
- Why is a line item with quantity = 0 created for the partially cancelled item '24932_2740433' in quote/breakup? There should only be one object with the remaining quantity.
@pranav-buynxt

**Comment by Jagannath-wits** [comment]
## Flow 1
#### on_search
- How is the timestamp of catalogue being updated? It should be updated whenever there is a change at that level i.e eg: if there is a change at item level then it’s timestamp should update and not at each on_search
- support for variants is mandatory
- invalid EAN code used in all domains

#### inc_search and inc_on_search
- missing payload

@pranav-buynxt

**Comment by Jagannath-wits** [comment]
## On_search
- Invalid attribute.value for material i.e ‘Black'
- attribute.value should be in lowercase i.e for colour_name should be ‘black’
- invalid ean code 12394981, please validate your EAN codes at https://eancheck.com/
- How is the timestamp of catalogue being updated? It should be updated whenever there is a change at that level i.e eg: if there is a change at item level then it’s timestamp should update and not at each. But here all item timestamps are same.
- multiple items with same variant have same attribute. Eg: Red, Black. Please create variants based on the individual item to avoid confusion.
@pranav-buynxt

**Comment by pranav-buynxt** [comment]
Sure, here's the response in a professional and clear manner:

---

1. **Invalid attribute value for material i.e. 'Black'**
   - **Response**: This issue has been fixed now.

2. **Attribute value should be in lowercase i.e. for colour_name it should be 'black'**
   - **Response**: All the colour_name values have been set to lowercase.

3. **Invalid EAN code 12394981, please validate your EAN codes at https://eancheck.com/**
   - **Response**: In the previous logs, the EAN code was invalid because it was a dummy store data. We have now added a valid EAN code to that data, validated using the provided tool.

4. **How is the timestamp of the catalog being updated? It should be updated whenever there is a change at that level i.e. if there is a change at item level then its timestamp should be updated and not at each. But here all item timestamps are the same.**
   - **Response**: The item timestamps were the same because we added the same date into the updated_date column as it was testing data.

5. **Multiple items with the same variant have the same attribute. Eg: Red, Black. Please create variants based on the individual item to avoid confusion.**
   - **Response**: Updated the variants based on individual items as suggested.


here is the PR Link of resubmitted logs for your reference -- `https://github.com/ONDC-Official/v1.2.0-logs/pull/2218`

@Jagannath-wits

**Comment by pranav-buynxt** [comment]
Hi  @sahil-ondc , 
We have implemented the provider changes, specifically the store opening and closing times, in the incremental call. As per my understanding, this is the only information we need to submit and if my understanding is incorrect, could you please clarify? It will be very helpful.

**Comment by Jagannath-wits** [comment]
flow 1
on_search
- categories.id should be alphanumeric upto 12 characters
- there should be atleast 2 items associated with a variant to be called a varaint.  Eg:E750AA73-A2F1-4983-8F03-C76B502A4708_gid_1 is associated with only 1 item
- invalid ean codes, please refrain from using placeholder values
- Attribute.material.value should be in lower case 
@pranav-buynxt

**Comment by Jagannath-wits** [comment]
## Flow 1
## on_search_full_catalog_refresh
- image url “https://greenreceipt.in/images/products/2854/NF17_1.png
“ is not accessible, check for others 
- item image and description dont match for item with id 26357_12394985, check for others
- Message Ids for /search and /on_search api should be same
- Invalid EAN code for item id 26357_12394985, check for others.

## Note : Please run utility before submission
@pranav-buynxt

**Comment by Jagannath-wits** [comment]
## Flow 1
### On Search
- Variants are not captured properly for the categories.id: 'Casserole_7' as the colour attribute is the same for both items with variants.
- colour and colour_name mismatch for item with id: '26357_12394986'. Please check for others and try not to create new errors while fixing old ones.

### On Search Inc

- The Items object is missing in the on_search_inc action call
- The item_id is also missing for the item created

@pranav-buynxt

**Comment by Jagannath-wits** [comment]
# Buynxt RET 16 (2024_09_24)

## Flow 1

### **on_search_full_catalog_refresh**

- `Categories.descriptor.name` should be meaningful.
- `message/catalog/bpp_providers/items/tags/code`: Material `attribute.value` should be in **lowercase letters**.

### **on_search_inc_store_open**

- `message/catalog/bpp~1providers/0/locations/0/time` must have the required property `schedule`.
- `message/catalog/bpp~1providers/0/locations/0/time/label` must be equal to one of the allowed values: `enable`, `disable`, or `close`.

### **on_search_inc_store_closed**

- `message/catalog/bpp~1providers/0/locations/0/time` must have the required property `schedule`.

---

### @pranav-buynxt  
## Please remove the older logs from the repo to avoid unnecessary confusion.

**Comment by sandeepshahi** [comment]
Logs approved for RET 16 (v1.2)

@pranav-buynxt
