### ISSUE TITLE
ShopEG (IGM) - compliance check

### ISSUE THREAD

**Issue by Rishabh-ondc** [ONDC-Official/v1.2.0-logs#225]
unsolicited on_issue_status
- please use actual/ near actual values for contact.phone
- respondent_action.updated_by.person.name and contact.email has changed, please check if it is intended implementation

@VijaiCPrasad

**Comment by BasanthVerma** [comment]
unsolicited on_issue_status

- Sure, We will ensure they are real numbers in production
- Yes it is intended depending on how many staff members we have on the team for support. If we only have one person then ideally this attribute will not change. Otherwise we're selecting one member's contact from the team to respond automatically with "processing" and then re-assign internally if needed to provide resolution.

@Rishabh-ondc

**Comment by Rishabh-ondc** [comment]
Logs cleared

@BasanthVerma @VijaiCPrasad
