### ISSUE TITLE
Cosmos (SA: RET10) - Compliance check

### ISSUE THREAD

**Issue by Jagannath-wits** [ONDC-Official/v1.2.0-logs#2253]
### On_search
- **Incorrect mapping:** Ensure category_id and items are correctly mapped. For example, 7up should not fall under the dairy and cheese category, and/or item names and descriptions should be accurate.
- **Timing tags:** The `tags.timing.type.value` should be set to 'All' if the timing is the same for all.
- **Invalid FSSAI and EAN number:** The provided catalog should be a subset of the production catalog.
- **Contact details:** The `@ondc/org/contact_details_consumer_care` contact number should consist of 10 or 11 digits without any spaces or special characters in `/bpp/providers[0]/items`.

### Inc_on_search
- **Examples needed:** Please provide an example of the following:
  - `on_search_incremental_provider_disable.json`
  - `on_search_incremental_store_closed.json`
  - `on_search_incremental_store_reopen.json`
  - `on_search_incremental_store_disable.json`
  - `on_search_incremental_catalog.json`

---

### on_select
- **Delivery item quote:** There is no need to add the delivery item in `quote.breakup` if the price is 0.

### on_init
- **Payment object:** Only `@ondc/org/buyer_app_finder_fee_type`, `@ondc/org/buyer_app_finder_fee_amount`, and `@ondc/org/settlement_details` are required in the payment object when the buyer is collecting money. Currently, only the buyer is collecting money on the network.
- **UPI Address:** Do not send `upi_address` when not required.
- **Message order tags:** `accept_bap_terms` is not required for now.
- **Provider tax number:** `provider_tax_number` must be present for `on_init`.

### confirm
- **Action error:** The `context.action` should be `confirm`.
- **Billing errors:** 
  - The key `created_at` should match between the `init` and `confirm` billing objects.
  - The key `updated_at` should also match between the `init` and `confirm` billing objects.
- **Order creation timestamp:** The `order.created_at` timestamp should match `context.timestamp`.
- **Payment updates:** 
  - `payment.collected_by` should be changed from BAP to BPP.
  - `payment.type` should be changed from `on-order` to `on-fulfillment`.

### on_confirm
- **Timestamp mismatch:** The timestamp for `/confirm` API cannot be greater than or equal to `/on_confirm`.
- **Order creation timestamp mismatch:** The `order.created_at` timestamp should match between `/confirm` and `/on_confirm`.
- **Tags list:** The `Pan_id` is different in `tax_number` and `provider_tax_number` in `message.order.tags.list`.
- **Payment object:** The payment object should match between `/confirm` and `/on_confirm`.
- **Transaction ID:** The `Transaction_id` is missing in `message/order/payment`.
- **BPP Terms:** The list of `bpp_terms` is mismatched in `message/order/tags/bpp_terms` between `on_init` and `on_confirm`.
- **Payment updates:** 
  - `payment.collected_by` should be changed from BPP to BAP.
  - `payment.type` should be changed from `on-fulfillment` to `on-order`.
- **TAT Calculation:** How are the `start` and `end` time ranges calculated if the TAT is 7 days?

### on_status_pending
- **Timestamp mismatch:** The `Created At` timestamp for `/on_status_pending` should be equal to `context.timestamp` at `confirm`.
- **Transaction ID:** The `Transaction_id` is missing in `message/order/payment`.

### on_status_packed
- **Timestamp mismatch:** The `Created At` timestamp for `/on_status_packed.message.order` should be equal to `context.timestamp` at `confirm`.

### on_status_picked
- **Timestamp mismatch:** The `Created At` timestamp for `/on_status_picked` should be equal to `context.timestamp` at `confirm`.

### on_status_out_for_delivery
- **Schema error:** `/message/order` must have the required property `documents`, i.e., the invoice should be carried forward.
- **Timestamp mismatch:** The `Created At` timestamp for `/on_status_out-for-delivery` should be equal to `context.timestamp` at `confirm`.

### on_status_delivered
- **Timestamp mismatch:** The `Created At` timestamp for `/on_status_delivered` should be equal to `context.timestamp` at `confirm`.

---

### select_out_of_stock
- **Cart update:** Please select multiple items and continue with what's left in the cart after `on_select_out_of_stock` as per the [rollout plan](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795).

---

### on_cancel
- **Cancel request:** The `cancel_request` comes in `delivery` fulfillment and not in `cancel` fulfillment.
- **Schema errors:**
  - `/context` must have the required property `ttl`.
  - The `Transaction_id` is missing in `message/order/payment`.

---

## Flow 5 - Please run the utility for each flow once before submission

---

### on_update_part_cancel
- **Schema errors:**
  - `/message/order/payment/params` must have the required property `transaction_id`.
  - The `Transaction_id` is missing in `message/order/payment`.

### update_settlement_part_cancel
- **Message ID:** The `Message id` should not be the same as previous calls.
- **Fulfillment ID:** The `Cancel fulfillment ID` should be the same as the one in the `/on_update` API.

### on_status_pending
- **Schema errors:**
  - `/context` must have the required property `ttl`.
  - `/message/order/fulfillments/1/tags/0/code` must be equal to one of the allowed values (`quote_trail`).
  - `/message/order/fulfillments/1/tags/0/list/0/code` must be equal to one of the allowed values (`type`, `id`, `currency`, `value`).
  - The `Transaction_id` is missing in `message/order/payment`.

### on_update_interim_liquidated
- **Schema errors:**
  - `/message/order/payment/params` must have the required property `transaction_id`.
  - The `Transaction_id` is missing in `message/order/payment`.
  - `message/order.payment/@ondc/org/settlement_details/0` is missing as compared to the previous calls or not captured correctly (e.g., `settlement_counterparty`, `settlement_phase`, `settlement_type`, `settlement_amount`, `settlement_timestamp`).
  - `message/order/fulfillments2/tags0` should have the `initiated_by` code in `fulfillments/tags/list`.

### on_update_liquidated
- **Schema errors:**
  - `/message/order/payment/params` must have the required property `transaction_id`.
  - The `Transaction_id` is missing in `message/order/payment`.
  - `message/order.payment/@ondc/org/settlement_details/0` is missing as compared to the previous calls or not captured correctly.
  - `message/order/fulfillments3/tags0` should have the `initiated_by` code in `fulfillments/tags/list`.
  - `initiated_by` should be `buyer-app-preprod-v2.ondc.org`.

### update_settlement_liquidated
- **Update error:** The JSON cannot be empty.

#### Will you only be supporting liquidation and not reverse-qc ?

@vijendrapatidar

**Comment by sandeepshahi** [comment]
- mocked requests should not be provided for verification (search requests (full and inc) appears to be mocked)

## Flow 1

**/on_search**

- why is serviceability defined for "Dairy and Cheese"?; no item is mapped to this category_id
- placeholder values of EAN code should not be provided
- "@ondc/org/contact_details_consumer_care" should be in correct format as mentioned in the contract (name, email, contact no) with contact no. of 10 or 11 digits
- categories/id should be alphanumeric and upto 12 characters
- values of statutory reqs are not captured correctly
- invalid attributes: "net_quantity_or_measure_of_commodity_in_pkg" and "imported_product_country_of_origin" provided in statutory_reqs

**/on_search (inc)**

- similar issues as above
- mocked payloads should not be submitted for verification; please test with a counterparty NP
- for above point, the seconds and milliseconds values can't remain unchanged for every unsolicited inc call
- how can context/timestamp be same for different incremental /on_search calls?

## Flow 2

**/on_select**

- delivery charge (with price = 0 if none is to be charged) should be included if the location is serviceable.

**/on_init**

- multiple issues in the payment object; placeholder values should not be provided
- for above point, only @ondc/org/buyer_app_finder_fee_type, @ondc/org/buyer_app_finder_fee_amount, and @ondc/org/settlement_details are required in the payment object; prepaid payment collection by BPP is currently not supported by BAPs

**/on_confirm**

- How can estimated pickup and delivery time ranges be provided when order is not yet accepted?

**/on_status**

- invoice is not correctly generated; the item is incorrectly shown as '7 up' based on the previous submission; values shouuld updated correctly in the DB, rather than being modified manually

## Flow 4

**/on_cancel**

- "cancel_request" tag should not be provided in "Cancel" type fulfillment
- invalid "quote_trail" line item with a "-0" value in /fulfillments; only the quote/breakup line items with delta changes should be provided in quote_trail
- schema of quote/breakup should not change for delivery and misc; /item is not valid for these line items
- quote_trail delta change for misc (convenience fee) is not captured correctly; type should be "misc" instead of "tax"

## Flow 5

**/on_cancel**

- estimated delivery time range should not change for cancelled forward shipment: "fulfillment-6386154b42674fabf7bdabf4"
- actual delivery timestamp can't be provided for RTO orders; invalid attribute /fulfillments/end/time/timestamp "fulfillment-6386154b42674fabf7bdabf4"

**/on_status (rto)**

- value of updated_at in precancel_state can't change
- RTO initiated timestamp can't change in type=RTO fulfillment; should remain the same as in /on_cancel
- rto delivered timestamp is missing in type=RTO fulfillment fulfillments/end/time/timestamp

## Flow 6

**/on_update (part cancel)**

- How can future refund info (for part cancelled item) be appended even before the FYI call is received from the BAP?
- the above info is missing in subsequent /on_status API

**/on_status**

- invoice is not generated correctly; why is part cancelled item (incorrectly named as "7 up") included in the invoice with wrong price value

**/on_update (liquidated)**

- similar issues with future refund related info, as mentioned above


@vijendrapatidar

**Comment by vijendrakiko** [comment]
Hi @sandeepshahi Please review this PR
https://github.com/ONDC-Official/v1.2.0-logs/pull/2262

**Comment by Gururaj-KikoLive** [comment]
Hi @sandeepshahi Please check new PR as discussed we've made changes and resubmitted 
https://github.com/ONDC-Official/v1.2.0-logs/pull/2282

**Comment by sandeepshahi** [comment]
## Flow 1

**/on_search**

- placeholder values of statutory reqs should not be provided
- invalid attribute: "imported_product_country_of_origin" provided in statutory_reqs

**/on_search (inc)**

- holidays should not be updated in inc refresh; schedule is not required

- incremental catalog
  - return window can't be 0 when returnable is true;
- store disable
  - disable should only be used for permanent closure; for temporary closure, use close/open

**/on_status (Pending)**

- estimated time ranges should be future dated; check start/time/range/start

## Flow 5

**/on_cancel**

- RTO intiation timestamp is not captured correctly; can't be the same as Out-for-delivery time

**/on_status (rto)**

- rto delivered timestamp is missing in type=RTO fulfillment fulfillments/end/time/timestamp


@Gururaj-KikoLive @vijendrakiko

**Comment by Gururaj-KikoLive** [comment]
Hi @sandeepshahi We've done the changes in our code please check for flow 1 for flow 5 we're sending in half n hour

**Comment by Gururaj-KikoLive** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/2285

@sandeepshahi Please check flow 1 & 5 updated

**Comment by sandeepshahi** [comment]
## Flow 1

**/on_search (inc)**

- please share the screenshot of seller panel for all the incremental refresh scenarios
- store close
  - start time of store closure is required in /time/range
- store reopen
  - store must be reopened using label = "open"

## Flow 5

**/on_status (Pending)**

- estimated time ranges should be future dated; check start/time/range/start


@vijendrakiko @Gururaj-KikoLive

**Comment by vijendrapatidar** [comment]
Thanks @sandeep
Sure We will send in some time.

**Comment by sandeepshahi** [comment]
Also, @vijendrakiko, have you implemented the catalog rejection framework feature?

**Comment by Gururaj-KikoLive** [comment]
Hi @sandeepshahi for /on_status (Pending)

estimated time ranges should be future dated; check start/time/range/start - Start time range start should we use of context timestamp?

**Comment by Gururaj-KikoLive** [comment]
@sandeepshahi Yes catalogue rejection framework is implemented

**Comment by vijendrapatidar** [comment]
Hi @sandeep
Please check this PR and Screen shot for store and item update functionality

https://github.com/ONDC-Official/v1.2.0-logs/pull/2287

**Comment by sandeepshahi** [comment]
@vijendrakiko, how can disabled store be closed later? Please check the sequence of the incremental catalogs and disable the other button in the UI accordingly.

**Comment by vijendrakiko** [comment]
Okay, we will do it now on the UI side.

**Comment by Gururaj-KikoLive** [comment]
@sandeepshahi Are there any additional requirements from your end? Please share them all at once so that we can prepare and respond accordingly. Addressing each point individually is causing significant delays. If we had known that video and screenshots were required during the initial review, we could have arranged for them simultaneously, which would have prevented unnecessary delays in the process.

**Comment by sandeepshahi** [comment]
@Gururaj-KikoLive, the only requirement is to provide the logs unaltered and as-is.

A video demo was requested in the last meeting as well. Additionally, since there were concerns that the screenshots might appear altered, we have asked for the video. Please address all the issues and ensure everything is thoroughly checked before submitting. This will help avoid any unnecessary back-and-forth. If the video demo takes some time, it might indicate that the requested features still need to be implemented.

**Comment by Gururaj-KikoLive** [comment]
Yes @sandeepshahi Our main goal is to address all identified and doubtful concerns all at once. We used a utility tool to clear the logs, and there were also some requested changes that were later reverted. It will just lead to a never-ending process for both of us, and neither of us will benefit from this. Our logs had flaws which we solved and resubmitted, but we are only concerned about newly arising requests and issues.

**Comment by Gururaj-KikoLive** [comment]
https://drive.google.com/drive/folders/1YZQ4Tqf3X5oD7mLXo-yRhhdBq82SJMx1?usp=sharing

@sandeepshahi Please check above videos,

**Comment by sandeepshahi** [comment]
Logs approved for v1.2.0

@Gururaj-KikoLive @vijendrakiko

**Comment by vijendrapatidar** [comment]
Thanks @sandeep
