### ISSUE TITLE
Paytm (BA) - compliance check

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.2.0-logs#24]
### Flows must be shared as per the [test case scenarios](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795)

**/search**

- request must be initiated for v1.2 with updated domain namespace
- /context must have required property 'ttl'

**/on_search**

- schema errors in the catalog; must be responded with a NACK
  - /message/catalog/bpp/providers/items/quantity/maximum/count must be string
  - /message/catalog/bpp/providers/items/quantity/available/count must be string
  - serviceability construct: value must be "country" ('c' in lower case) for code "unit"
- transaction_id and message_id mismatches between /search and /on_search

#### - "ttl" and "city" missing in /context

**/select**

- selected provider doesn't exist in the catalog

**/confirm**

- fulfillments/start is not required
- /message/order must have required property 'state'
- context/transaction_id must remain the same from /select onwards
- address/country, created_at, updated_at mismatches in /billing in /init and /confirm
- estimated pickup and delivery time ranges can't be provided by the buyer app
- buyer app finder fee should not change; /on_init must be reponded with a NACK otherwise

**/status**

- initiate a request for v1.2 with updated domain namespaces

**/update (as per the revised flow)**

- txn id mismatches; entire txn flow must be submitted for verification;
- /on_update callback response for same txn must be submitted for verification
- fulfillments/type must be "Return" (instead of "return")

**/cancel**

- txn id mismatches; entire txn flow must be submitted for verification;
- /on_cancel callback response for same txn must be submitted for verification

@chiragkhannapaytm

**Comment by bluecypher** [comment]
- context/ttl must be PT30S
- RET domain namespace should be used (for testing in pre-prod)

**/select**

- fulfillments/end/location is outside the serviceability region of the provider for category= F&B

**/confirm**

- estimated delivery time range (fulfillments/end/time) can't be provided by the buyer app
- instructions, "@ondc/org/TAT", provider_id are not required in /fulfillments
- value of tracking attribute can't be changed by the buyer app
- buyer app finder fee should not change; /on_init must be reponded with a NACK otherwise
- quantity attribute is not required in /quote/breakup/item
- tax_number in bpp_terms is missing in /on_init; should be NACK'd by BNP
- accepting/rejecting BPP terms should be removed, since BPP terms are not provided in /on_init; +static terms are not part of phase 1
- invalid code property "fixed_terms"; also, static terms are not part of phase 1

**/on_confirm**

- respective GST numbers in bpp_terms and bap_terms are not replicated by SNP; should be NACK'd by BNP

**/update**

- refund should only be triggered once refund triggering state is received from the SNP;

**/on_update (liquidated)**

- updated quote is not provided as per the quote_trail;


@chiragkhannapaytm

**Comment by bluecypher** [comment]
**/search**

- ttl should be PT30S

**/search (incremental)**

- tags/list can't be empty; either one of 1-time incremental or regular incremental should be initiated

**/select**

- selected provider doesn't exist in the catalog

**/select (multi item)**

- transaction_id of /select and /select for OOS should be the same
- schema of /on_select (OOS) is incorrect, price/value should be string; should be NACK'd by BNP

**/confirm**

- value of tracking attribute can't be changed by the buyer app

**/update**

- refund should only be triggered once refund triggering state is received from the SNP;

**/status**

- /message/order is invalid object; should be /message/order_id


@chiragkhannapaytm

**Comment by bluecypher** [comment]
### - Logs must be submitted as per the test case scenarios (Flow Wise) in separate folder

### - Logs should be shared with customizations/variants in the cart

**/search (incremental)**

- invalid value of context/timestamp; can't have spaces
- ttl is missing in /context
- one time incremental refresh must also be supported
- regular incremental refresh must be stopped at a later time

**/select**

- context/city is not captured correctly; should be mapped as per the seller's location

**/select (OOS)**

- city, domain, timestamp in context can't have spaces
- context/transaction_id of /select and /select (OOS) should be the same

**/on_select**

- discount must be supported by BNP
- OOS: schema is not correct; price/value should be in string format

**/init**

- billing/name and billing/address/name can't be same
- tracking value can't be changed

**/confirm**

- invalid code property "fixed_terms"; also, static terms are not part of phase 1

**/cancel**

- context/action should be "cancel"
- "005" is not a valid "cancellation_reason_id" initiated by BNP

@chiragkhannapaytm

**Comment by sharmasahil0331** [comment]
**confirm**

- message/order/tags must have required property 'bap_terms'
- billing object mismatch from on_init

**cancel**

- /message must have required property 'descriptor'

### Suggestive (BNP should handle)

**on_search_full_catalog_refresh**

- /message/catalog/bpp~1providers/0/items must have required property 'quantity'
- 'time_to' must be greater than 'time_from', (provided 'time_from':'1000' and 'time_to':'0400')

**on_init**

- /message/order must have required property 'tags'
- billing object mismatch 'address.country' mismatch: India !== IND

@chiragkhannapaytm

**Comment by BLR-0118** [comment]
Buyer App -> Normal Flow
=================
1. Full_On_Search:
- all base items (e.g. ids 2455688 / 2455695 / 2455702 / 2455709 /2455716) have price of 0 & neither default selection price or min/max range is available: what price is displayed on the provider listing page for these products?
- since no customization group has default customization, what happens when buyer checks out from the provider listing page?
2. Incremental_Search start/stop have different transaction ids. Need the jira ticket no & date by which this will be fixed;
3. Incremental_On_Search only has provider disable. Are the following supported:
- location close (with start & end time);
- location close (with only start time) & subsequent reopen thru incremental / full refresh;
- item record update;
4. Are both incremental pull & push supported? If yes, what frequency of incremental push is supported?
5. Is tracking supported?

**Comment by BLR-0118** [comment]
@chiragkhannapaytm

**Comment by ravi-kumar-yadav** [comment]
@BLR-0118: Please find the responses below:


S.No. | Raw Output log by ONDC Utility | APIName | Issue
-- | -- | -- | --
1 | all base items (e.g. ids 2455688 / 2455695 / 2455702 / 2455709 /2455716) have price of 0 & neither default selection price or min/max range is available: what price is displayed on the provider listing page for these products? | on_search | Price range is not shown in UIPaytm show only max_value and value (to compute and display discount)
2 | since no customization group has default customization, what happens when buyer checks out from the provider listing page? | on_search | Customer needs to select (even for mandatory customization group)
3 | Incremental_Search start/stop have different transaction ids. Need the jira ticket no & date by which this will be fixed; | incremental_on_search | Cohort Jira: PROD-3771
4 | Incremental_On_Search only has provider disable. Are the following supported:location close (with start & end time); | incremental_on_search | supported and live in production
5 | location close (with only start time) & subsequent reopen thru incremental / full refresh; | incremental_on_search | supported and live in production
6 | item record update; | incremental_on_search | supported and live in production
7 | Are both incremental pull & push supported? If yes, what frequency of incremental push is supported? | incremental_on_search | Only incremental push is supported as of nowfrequency: once a day

**Comment by Anupam1705** [comment]
@BLR-0118 Can you please check @ravi-kumar-yadav comments and share us action item if any.

**Comment by BLR-0118** [comment]
1. if seller NP is sending catalog with base item price of 0 (but with default selection price, lower/upper price range), it should be honoured; if they're not sending, you can use your logic. Is this being followed?
2. if seller NP sends a customization as the default for customization group, is that displayed in the customization popup?

**Comment by BLR-0118** [comment]
@ravi-kumar-yadav @Anupam1705

**Comment by ravi-kumar-yadav** [comment]
@BLR-0118: 

if seller NP is sending catalog with base item price of 0 (but with default selection price, lower/upper price range), it should be honoured; if they're not sending, you can use your logic. Is this being followed?
- Currently price range isn't being shown to user


if seller NP sends a customization as the default for customization group, is that displayed in the customization popup?
- customization is always show to customer in popup even if it's the default for customization group

**Comment by ravi-kumar-yadav** [comment]
@BLR-0118 
As discussed we will be picking above requested task in near future, please find the corresponding COHORT Jira below:

if seller NP is sending catalog with base item price of 0 (but with default selection price, lower/upper price range), it should be honoured; if they're not sending, you can use your logic. Is this being followed?
-customization is always show to the user in popup (even if it's the default for given customization group)
https://ondc-issue-logging-cohort1.atlassian.net/browse/PROD-3878 


if seller NP sends a customization as the default for customization group, is that displayed in the customization popup?
- https://ondc-issue-logging-cohort1.atlassian.net/browse/PROD-3879

**Comment by BLR-0118** [comment]
@ravi-kumar-yadav - is Paytm buyer app supporting tracking?

**Comment by ravi-kumar-yadav** [comment]
@BLR-0118: Paytm BuyerApp supports tracking

**Comment by ravi-kumar-yadav** [comment]
@BLR-0118 As discussed, we have already submitted logs for /track and /on_track as part of Paytm SellerApp v1.2 logs. As Paytm SellerApp had generated these logs (track and on_track) with Paytm BuyerApp, we will be submitting same set of logs (for /track and /on_track).

@chiragkhannapaytm Please submit /track /on_track logs for Paytm BuyerApp too (ref: Paytm SellerApp submitted logs).

**Comment by chiragkhannapaytm** [comment]
Hi team ,
Please find below the PR with tracking logs.
https://github.com/ONDC-Official/v1.2.0-logs/pull/413

Thanks & Regards
Chirag Khanna

**Comment by BLR-0118** [comment]
As discussed with Paytm team, pls submit logs for /search & /on_search for all supported categories (except F&B which has been verified) - grocery, fashion, BPC, Electronics, H&K, H&W;
@chiragkhannapaytm

**Comment by chiragkhannapaytm** [comment]
Hi team ,
Please find below the search/on_search logs for ONDC:RET12 (fashion) and
ONDC:RET10 (grocery)
https://github.com/ONDC-Official/v1.2.0-logs/pull/483

Regards
Chirag Khanna

**Comment by BLR-0118** [comment]
logs cleared for grocery (RET10), F&B (RET11), fashion (RET12)

**Comment by BLR-0118** [comment]
pls note that the logs submitted for RET10 & RET12 are slightly older versions from these NPs with these issues:

RET10
====
1. categories definition for "variant_group" type:
- attr.name should point to namespaced attribute e.g. "item.quantity.unitized.measure";
- some of the values used for item.quantity.unitized.measure.unit are wrong e.g. "ml" instead of "millilitre", "grams" instead of "gram", etc; the enum list referenced in the contract is [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json);

RET12
====
1. invalid item.category_id of "undefined";
2. invalid value of item.quantity.unitized.measure.value;

@chiragkhannapaytm - I've discussed the above with Amit. Pls make sure this is taken care of.

**Comment by chiragkhannapaytm** [comment]
Hi team
Please find below the search/on_search logs for ONDC:RET13 (BPC) and
ONDC:RET14 (Electronics)
https://github.com/ONDC-Official/v1.2.0-logs/pull/557
<https://github.com/ONDC-Official/v1.2.0-logs/pull/483>

<https://github.com/ONDC-Official/v1.2.0-logs/pull/483>
Thanks and Regards
Chirag Khanna

**Comment by chiragkhannapaytm** [comment]
Hi team
Please find below the search/on_search logs for ONDC:RET16  and ONDC:RET18
https://github.com/ONDC-Official/v1.2.0-logs/pull/590

Regards
Chirag Khanna

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 for RET13, RET14, RET16, RET18
