### ISSUE TITLE
PepsiStore (RET10) - compliance checks

### ISSUE THREAD

**Issue by bluecypher** [ONDC-Official/v1.2.0-logs#336]
## Flow 1

**/on_search**

- search is initiated for gurugram city; seller's location must be of the same city
- /search should be provided for same txn
- fssai license no is not required for grocery domain
- available count of item should be either 99 or 0 indicating the availability of inventory
- maximum/count of item should be in string format
- maixmum count should be either 99 (no cap) or any +ve value (max cap)
- duplicate "code": "veg_nonveg" should be removed for an item
- "imported_product_country_of_origin" is not a part of "@ondc/org/statutory_reqs_prepackaged_food" in /items

## Flow 2

**/on_select**

- available and maximum count in quote/breakup have the same logic as in /on_search catalog

**/on_init**

- tax_number can't be empty in /tags/bpp_terms
- buyer app finder fee amount can't be empty in /payment

**/on_confirm**

- tax_number can't be empty in bpp_terms and bap_terms

**/on_status**

- quantity/count should be in integer format in /items
- created and updated timestamps can't change in /billing; should remain the same as in /init call
- count in /"@ondc/org/item_quantity" should be in integer format

## Flow 3

**/on_select (OOS)**

- count in /@ondc/org/item_quantity should be 0 for OOS item(s)
- error.message should be in the correct format as mentioned in the contract

## Flow 4

**/cancel**

- invalid cancellation reason code "012" (can't be used by BNP); should be NACK'd by SNP

**/on_cancel**

- quote/price/value should be equal to sum of quote/breakup price
- delivery charges should also be adjusted in the quote_trail; since quote/price/value=0
- updated_at in tags/precancel_state is not captured correctly;

## Flow 5

- RTO should be initiated as per flow 5

@quantummach14

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- available count of item should be either 99 or 0 indicating only the availability of inventory and not the actual count
- maximum count should be either 99 (no cap) or any +ve value (max cap)
- valid "unit" should be provided in quantity/unitized/measure/unit; eg- "L" is not a valid enum; should be litre
- use non-deprecated value of [category_id](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0)
- invalid store location details provided for location: "S01433844-BGLR"; seller location must be of std:080 (for which search initiated)

**/on_search (incremental)**

- callback response should not take longer
- item enable/disable timestamp is missing
- no incremental changes in the catalog; should be initiated after full catalog

## Flow 2

**/on_select**

- available and maximum count in quote/breakup have the same logic as in /on_search catalog

**/on_init**

- billing object should remain the same in /init and /on_init;

**/on_confirm**

- "@ondc/org/TAT" should be provided /fulfillments
- address is missing in /fulfillments/start/location
- tax_number in bap_terms is not valid; should be the same as shared by the buyer app
- cancellation_terms are missing in /on_init;

## Flow 3

**/on_select (OOS)**

- error.message should be in the correct format as mentioned in the contract

## Flow 4

**/on_cancel**

- quote/price/value should be in string format
- delivery charges should also be adjusted in the quote_trail; since order is not even packed (delivery fee should not be charged from buyer)
- "Accepted" is not a valid fulfillment state in /tags/precancel_state; valid fulfillment state should be provided instead of order/state

## Flow 5

- retry_count and rto_id are missing in /tags/cancel_request
- precancel_state is not valid in /tags
- updated_at timestamp is not captured correctly in /tags/precancel_state
- For RTO fulfillment, type should be RTO;
- check on_cancel (RTO flow) in contract for correct schema


@quantummach14

**Comment by BLR-0118** [comment]
Full Catalog - on_search
================
- "tags" with "np_type", etc. should be inside "bpp/descriptor", not under "Catalog" (also remove "accept_bap_terms" from here as this will be enabled later);
- item.quantity.unitized.measure.unit of "grams", "Kg" is invalid (should be "gram" as per [this](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json) list) (correct unit of "gram" has also been used for many items);
- item.id such as "59374/59821/59910" will be a problem (better to have alphanumeric, if you need delimiters use "-");
-  for item 58781, available qty of 0 means out of stock, but what does max qty of 0 mean?
- for item 4094, item.quantity.unitized.measure.unit of "ml" is invalid; for value instead of "250x6", why not use "1500"?
- check images for item 8901058904093;
- no use of variants for better buyer experience?

Incremental Catalog - on_search
=====================
- every message should have an unique message_id; hence, for the incremental updates, are you assigning an unique message_id for every /on_search (couldn't verify as there's only 1 incremental /on_search provided);
- are you supporting incremental pull, where both start & end timings are specified in /search?

Flow 2
====
1. /on_init:
- remove everything from bpp_terms except tax_number (will be enabled later);

2. /on_confirm:
- remove cancellation_terms (will be enabled later);
- structure of bap_terms (with tax_number) incorrect;
- can you also pass provider_tax_number inside bpp_terms for the buyer app to verify whether you're MSN or ISN?

Flow 4
====
1. /on_cancel:
- inconsistency between total quote (quote.price.value) and breakup: total quote is 0 but breakup includes non-zero delivery charge;
- why does quote_trail have "50" as delivery charge (should be -50 as per quote.price.value);

Flow 5
====
1. inconsistency between /on_confirm & unsolicited on_cancel:
- in /on_confirm, there are 2 items (57759, 59823), each with qty 2; however, /on_cancel items array shows qty 3 for 59007??
- if there's RTO delivery charge being added, it should also be added to quote_trail for the fulfillment;

**Comment by BLR-0118** [comment]
@quantummach14 - pls fix & resubmit logs only for issues above;

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- major buyer apps will have validations for item.quantity.unitized.measure.value; hence, following will fail:
- "250x6" for item 4094 & others (if "1500 millilitre" isn't possible, can you try - "6 unit" and to the desc add "250 ml");
- "1 N" for item 8901255000444 (this looks like "1 unit"?
- provider (8cdf6c74-8b95-4da1-9caa-3a0a5edd2508), locn (S01433844-BGLR) shows city of Bengaluru but pincode of 122018;

Flow 5
====
- pls also share the /on_cancel payload;

pls suggest how Flow 1 issues can be resolved; also I'm assuming /on_cancel in flow 5 is fixed (since /on_cancel in flow 4 is correct)

**Comment by BLR-0118** [comment]
@quantummach14 - what are your plans to enable variants?

**Comment by quantummach14** [comment]
Uploaded revised logs. PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/536

what are your plans to enable variants? : We are working on this. By end of Jan we shall implement

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search:
- item.id of "Product discountinue" seems different from other ids. If you're discontinuing an item, you can set it to "disable" in full or incremental catalog refresh;

Flow 5
====
1. /on_cancel:
- quote_trail is correct but quote.price is wrong (shouldn't it be 100)?
- since retry attempts are being made, shouldn't precancel_state be "Out-for-delivery" instead of "Pending"?

**Comment by BLR-0118** [comment]
clearing logs for 1.2 (RET10) subject to the above being fixed
