### ISSUE TITLE
Otipy (Seller App) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#339]
### Flow 1

**search_inc_refresh**

- context/city should be '\*' while sending search_inc_catalog request
- context/domain should be same as context/domain provided in search_full_catalog_refresh

**on_search_full_catalog_refresh**

- /message/catalog/bpp/providers/@ondc/org/fssai_license_no must NOT have fewer than 14 characters
- /message/catalog/bpp/providers/locations/address/area_code must NOT have fewer than 6 characters
- store enable/disable timestamp (/bpp/providers/time/timestamp) should be less then or equal to context.timestamp
- fulfillment_id in /bpp/providers/items should map to one of the fulfillments id in bpp/fulfillments
- /message/catalog/bpp/providers/items/category_id must be equal to one of the allowed values
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=403839701`

**on_search_inc_refresh**

- Similar Item as in /on_search_full_catalog_refresh api call, item id- 9343

### Other Flows

**init**

- address.building should be more than 3 chars

**on_init**

- gps coordinates in fulfillments[0].end.location mismatch in /select & /on_init

**on_confirm**

- context/timestamp difference between /on_confirm and /confirm should be smaller than 5 sec
- billing issues
  - Key 'address.locality' mismatch: Hansraj Gupta Marg !== Greater Kailash Road
  - Key 'created_at' mismatch: 2023-12-14T07:52:58.535Z !== 2023-12-14T09:59:53.031Z
  - Key 'updated_at' mismatch: 2023-12-14T07:52:58.535Z !== 2023-12-14T09:59:53.031Z
  - store gps location /fulfillments[0]/start/location/gps can't change
  - fulfillments[0].end.location gps is not matching with gps in /select

**on_status**

- /message/order/fulfillments/0/start must have required property 'time'
- /message/order/fulfillments/0/end must have required property 'time'

@yashCrofarm

**Comment by sahil-ondc** [comment]
## Flow 1

**on_search_full_catalog_refresh**

- /message/catalog/bpp_providers/locations must have property circle in case of serviceability type '10'

## Other flows

**select**

- Timestamp for /on_search api cannot be greater than or equal to /select api

**on_select**

- packing charge, discount, misc to be included only if not 0, as mentioned in the API contract

**init**

- address.building should be more than 3 chars

**on_init**

- gps coordinates in fulfillments[0].end.location mismatch in /select & /on_init



## Note

Kindly submit logs with variant groups, and please refresh your catalog before order flow 

@yashCrofarm

**Comment by shiv0018** [comment]
Hi @sahil-ondc pls find my comments below:
1. We were initially adding the "circle" property in the /message/catalog/bpp_providers/locations. But as per the log validation utility testing, we had to remove it as it was showing error for the circle. I think it should not be a concerned issue.
2. On the reference app, search runs only with a certain frequency. So the timestamp of search & select might be different. Pls don't consider that validation issue for correction.
3. For packaging/misc/delivery charges, there was no specific validation mentioned earlier in the api document, so we developed it keeping it visible even with zero value.
4. int address 3 char issue. This is saved at reference app, there was no validation for minimum characters, that's why its appearing here. It is buyer app side property.
5. GPS coordinate mismatch. This is again buyer side issue, which sends coordinates with different value (decimal mismatch). This is not our issue. It was discussed with Sandeep already, and he agreed on this.
6. For our business and the kind of catalogue we have, there are not variants available. This was discussed way long back with the ONDC business team and they were comfortable having products without variants. So all the variants related test cases will not be eligible for us.
Kindly approve the logs.

**Comment by vipul-jn** [comment]
@sahil-ondc : Is it possible, that the changes you have mentioned... we will do the changes in the flow 2, instead of running all the test cases again and capturing it.

**Comment by yashCrofarm** [comment]
@sahil-ondc kindly find the corrections below.
 https://github.com/ONDC-Official/v1.2.0-logs/pull/365/

**Comment by CharanpreetChawla** [comment]
## Flow 1

**/on_search_inc_refresh**
- Similar Item as in /on_search_full_catalog_refresh api call, item id- 9371

**/confirm**
- /message/order/fulfillments/0 must have required property 'tracking'
- Tags/bap_terms should have valid gst number and fields in /confirm

**/on_confirm**
- Tags should have same and valid gst_number as passed in /confirm

**Comment by shiv0018** [comment]
Hi @CharanpreetChawla Please find my comments below
1. /on_search_inc_refresh - In Increment change there was a price change so we sent same item with price change.
 
2. /confirm -  We are seller ISN and we got confirm request from ONDC reference buyer app (bap_id-buyer-app-preprod-v2.ondc.org). So In confirm API we submitted same request body which we got from reference buyer app. So this is buyer app side issue not seller side.

3. /on_confirm - As per ONDC-API contract for seller(v1.2.0) we should receive same tags in confirm api which we sent in on_init api. But we did not received same tags in confirm. We sent same tags in on_init and on_confirm. 
 
Kindly review my comments and verify the logs.

**Comment by vipul-jn** [comment]
@sahil-ondc @bluecypher Pls review the logs.. as we have already discussed that the comments related to the buyer apps will be ignored as we have tested it from the buyer app.

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- timestamp can't be earlier than /search timestamp
- "collect_payment" tag is optional; may be provided if seller NP wants to collect payment;
- fulfillment id should be the same in bpp/fulfillments and bpp/providers/fulfillments; already discussed earlier

**/on_search (incremental)**

- no incremental delta changes

## Flow 2

**/on_init**

- provider_location attribute is not required; should be removed
- type, collected_by, uri (payment link), status, settlement_basis, settlement_window, withholding_amount should only be provided when seller NP is collecting pre-paid payment
- incorrect schema for cancellation_terms; + should not be provided, since not a part of phase 1
- only tax_number is required in bpp_terms (remaining terms are not yet required)

**/on_status**

- TAT provided in /on_select is 1 Day; estimated pickup and delivery time ranges are not in sync with that TAT; should be updated in either of the calls
- all the fulfillment states must be provided as unsolicited calls
- "@ondc/org/TAT" mismatches in /on_select and /on_status
- actual pickup timestamp (/fulfillments/start/time/timestamp) should not change in Out-for_delivery and later states; should be captured from Order-picked-up state
- estimated pickup (fulfillments/start/time/range) and delivery (fulfillments/end/time/range) timestamps should not change
- Invoice url should not change in subsequent unsolicited calls

## Flow 3

- similar issues as above

## Flow 4

- similar issues as above

**/on_confirm**

- tax, discount, packing, misc line items should not be provided if price=0;

**/on_cancel**

- "012" is invalid cancellation reason id (can only be initiated by SNP or LSP); should be NACK'd by SNP
- "@ondc/org/item_id" = "F1-RTO" is not a valid fulfillment id used in quote/breakup
- why is quote_trail added for fulfillment id "C1"?
- quote_trail schema is incorrect; separate quote_trail block should be provided for any adjustment in quote line item (item, delivery, packing etc.)
- timestamp in /fulfillments for type = "Cancel" can't be future dated; should be <= context/timestamp

## Flow 5

- No unsolicited cancellation to initiate the RTO
- similar issues as above


@vipul-jn

**Comment by shiv0018** [comment]
@bluecypher Please review the logs. we resubmitted the correct logs as per your suggestions.

**Comment by CharanpreetChawla** [comment]
Working on it

**Comment by shiv0018** [comment]
@CharanpreetChawla any update ??

**Comment by shiv0018** [comment]
@CharanpreetChawla 
**Flow 1**
There are two items with delta changes. In first item (id-9341),  item label is changed to disable form enable. In second item (id-9371),  item price is changed from INR 26 to INR 20.

**Flow 2 and 3**
Please refer to the comments made by @bluecypher . He suggested us to not send these extra keys because we are not collecting payment. Buyer will handle the payment collection part.

** Flow 4**
As per API contract for retail v1.2.0(Page no. - 440 to 441.) there is quote trail in fulfillment object C1.
For timestamp in /fulfillments for type = "Cancel"  we will correct this. 

**Flow5**
Same as flow 2 and 3.

**Comment by shiv0018** [comment]
@CharanpreetChawla @bluecypher  Please review my comments and let me know if any other information required.

**Comment by bluecypher** [comment]
@shiv0018, the properties are mandatory in /on_confirm.

**Comment by vipul-jn** [comment]
@bluecypher Even I remember, you suggested to remove those payment related blocks as we are not collecting the payment. How come it is mandatory now!

**Comment by yashCrofarm** [comment]
@bluecypher @CharanpreetChawla 
Kindly find the link to PR after suggested changes
https://github.com/ONDC-Official/v1.2.0-logs/pull/498

**Comment by bluecypher** [comment]
## Flow 1

**/on_search**

- location/category/type codes are not required in the list for parent code "order_value";

**/on_confirm**

- @ondc/org/TAT is missing in /fulfillments

## Flow 5

**/on_cancel (RTO-disposed)**

- invalid call; /on_status must be used to provide status updates for RTO
- why are item objects duplicated in /items?
- quote_trail is invalid; check previously identified issues

## Flow 6

**/on_update (part cancel)**

- forward shipment mapping must be present for item 9341 in /items with count=0
- why is part cancellation with reason id 002 initiated after the order is picked? (on_status is also missing for Order-picked-up state)

**/on_update (Return_Initiated)**

- context/timestamp can't be earlier than /update timestamp
- subscriber_id of buyer app should be provided in "initiated_by" for fulfillment type = "Return"

**/on_update (Liquidated)**

- context/message_id should be unique for every unsolicited call
- quote_trail should only be provided where quote amount is getting adjusted; should be removed where value=0 (eg: tax)


@yashCrofarm @vipul-jn

**Comment by vipul-jn** [comment]
New PR with the fixes : https://github.com/ONDC-Official/v1.2.0-logs/pull/537
@bluecypher

**Comment by shiv0018** [comment]
@bluecypher Can you please review this PR : #537

**Comment by bluecypher** [comment]
**/on_select**

- time_to_ship (in catalog) can't be the same as delivery TAT @ondc/org/TAT;

**/on_cancel**

- precancel_state must be provided in /fulfillments

**/on_status (RTO-Disposed)**

- RTO Initiation timestamp (/fulfillments/start/time/timestamp for type = "RTO") should not change

**/update**

- FYI update call with refund details are missing


@shiv0018 @vipul-jn

**Comment by vipul-jn** [comment]
@bluecypher can we setup a call for discussion of the comments.

**Comment by vipul-jn** [comment]
PR with changes : https://github.com/ONDC-Official/v1.2.0-logs/pull/585

**Comment by vipul-jn** [comment]
@bluecypher

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_select:
- definition of item.quantity.available.count is "99" (in-stock) or "0" (out-of-stock); this is correctly followed in /on_search, but in /on_select, it becomes "3";
2. /on_status:
- didn't see an /on_status for "Packed", just wanted to check if this is also being sent? Buyer apps have validations in place, so states can't be skipped;

Flow 3
====
1. /on_select (out of stock):
- error.message: pls use escaped double quotes instead of single quotes as updated in contract;

Flow 5
====
1. /on_cancel (rto initiated):
- pls only include delta changes in quote_trail (e.g. RTO delivery charges are not being applied, so shouldn't be here);
- pls also include precancel_state;

**Comment by BLR-0118** [comment]
@yashCrofarm - pls fix the above & make a note here when done; logs don't need to be resubmitted;

**Comment by BLR-0118** [comment]
log cleared for v1.2.0 (RET10)
