### ISSUE TITLE
ITCStore - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#407]
Flow 1
====
1. /on_search:
- tags (code="bpp_terms") is under bpp/descriptor, not catalog;
- remove "accept_bap_terms", "collect_payment" from "bpp_terms" until it's enabled;
- variant definition is invalid: namespaced attribute name has to be given for "attr" (in this case - item.quantity.unitized.measure, not "grams");
- variant defined above should be used to group items by assigning variant grouping id to item.parent_item_id;
- item ids with spaces & other literals like "&" will be problematic (e.g. "AASHIRVAAD CHPWRWTGUNTUR&BYCH100G");
- item.quantity.available.count should have default value of "99" (means - in stock) or "0" (out of stock);
- similarly, item.quantity.maximum.count should have default value of "99" (means - no cap per order) or a non-zero value that identifies the cap per order;
- category id "Beauty & Hygiene" should go under BPC (RET13);
- "contact_details_consumer_care" should be in this format - "name, email, contact no";

2. /on_search_inc:
- not sure what exactly is being updated for the items (price, inventory, etc. are same as in full catalog) - only delta updates from full catalog should be pushed in incremental update;

Flow 2
====
3. /on_init, /on_confirm:
- remove everything from bpp_terms (except tax_number, provider_tax_number - to be added in /on_confirm);

Flow 3 - ok;

Flow 4 & 5 - logs to be submitted;

**Comment by BLR-0118** [comment]
@ITCStore - pls resubmit logs only for issues above

**Comment by ITCStore** [comment]
@BLR-0118 Flow 4& 5 logs are there in pull request: https://github.com/ONDC-Official/v1.2.0-logs/pull/379/files

**Comment by ITCStore** [comment]
@BLR-0118 /on_search_inc: we pushed inventory. there was a change in the inventory count. Currently, below scenarios are being used to trigger inc_push:
Change in inventory
Change in price
Product disabled/OOS

**Comment by BLR-0118** [comment]
Pt 2 above:
- SNP only communicates whether an item is in stock (default value - "99") or out of stock (default value - "0");
- since actual inventory count is not communicated over the protocol, you shouldn't be updating this value in incremental update;
- for maximum count, the default value ("99") means no cap per order; any other >0 value means there's a cap per order;

Flow 4 - ok;

Flow 5
====
1. /on_cancel:
- precancel_state is actually the state for forward shipment fulfillment prior to being cancelled;
- why is the RTO delivery charge added twice in quote trail?

Also, how are you differentiating between normal cancel & RTO cancel? Since the reason code "012" used for normal cancel can also trigger RTO as per the reason code definition [here](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031);

**Comment by BLR-0118** [comment]
Flow 1
====
1. Full catalog /on_search:
- for item ASCW*: value > maximum_value;
- for item MD100SAND, quantity.unitized.measure.value not provided;
- for items such as this ASATTAMP5KG (and others grouped by variant), why not use "kilogram" instead of grams as it's a valid [unit of measure](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json);

2. Incremental /on_search:
- for item "NACHOS RS10 CHEESE" for which price has been updated, why is item.quantity.unitized.measure.value showing "25" for full catalog and "25.000000" for incremental? Isn't this the same value from the catalog?
- every message should have an unique message_id; hence, for the incremental updates, are you assigning an unique message_id for every /on_search (couldn't verify as there's only 1 incremental /on_search provided);

3. Curious why for both full & incremental /on_search, you're escaping most of the forward slashes "/"?

Flow 2
====
1. /on_confirm:
- pls also send provider_tax_number for the BNP to verify that you're an ISN;

Flow 5
====
1. /on_cancel_RTO:
- quote trail for id "57741d11-ac93-46cc-bf4b-7593e7281b4d-RTO" is repeated twice;
- request you to add precancel_state (state before it was cancelled) to forward shipment fulfillment also;

**Comment by BLR-0118** [comment]
@ITCStore - logs don't need to be resubmitted; pls add a note here after fixing the above, so I can clear the logs;

**Comment by quantummach14** [comment]
@BLR-0118 Please find my comments inline below:
**Flow 1**

Full catalog /on_search:
for item ASCW*: value > maximum_value : **Rectified**
for item MD100SAND, quantity.unitized.measure.value not provided : **Value against this SKU is not pushed from our WMS. This is rectified in the live product master.**
for items such as this ASATTAMP5KG (and others grouped by variant), why not use "kilogram" instead of grams as it's a valid [unit of measure](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json) - note "grams" is invalid but "gram" is : We are getting Units from our central system. I have changed grams to gram. 
Incremental /on_search:
for item "NACHOS RS10 CHEESE" for which price has been updated, why is item.quantity.unitized.measure.value showing "25" for full catalog and "25.000000" for incremental? Isn't this the same value from the catalog? : **Yes. We are removing additional zeros from value in full catalog pull but changes not done in incremental catalog. Changes now implemented.**
every message should have an unique message_id; hence, for the incremental updates, are you assigning an unique message_id for every /on_search (couldn't verify as there's only 1 incremental /on_search provided); : Yes
Curious why for both full & incremental /on_search, you're escaping most of the forward slashes "/"?
Are you supporting incremental pull (where /search has both start & end timings)? : Yes we are supporting.


**Flow 2**

/on_confirm:
pls also send provider_tax_number for the BNP to verify that you're an ISN; **DONE**


**Flow 5**

/on_cancel_RTO:
quote trail for id "57741d11-ac93-46cc-bf4b-7593e7281b4d-RTO" is repeated twice; **Rectified**
request you to add precancel_state (state before it was cancelled) to forward shipment fulfillment also; **Added.**

**Comment by BLR-0118** [comment]
logs cleared for grocery (RET10)

**Comment by quantummach14** [comment]
@BLR-0118 Do we need to submit the logs for Beauty & Hygiene as well
