### ISSUE TITLE
Dehaat BA & SA (AGR10) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#570]
### on_search

- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format
- Either one of fixed (range) or split (frequency and times) timings should be provided in /bpp/providers[0]/locations[0]/time

### select

- message/order/fulfillments/0/end/location must have required property 'address'

### on_select

- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

### on_init

- /message/order/billing/address must have required property 'building'
- message/order/fulfillments/0/end/location/address must have required property 'building'

### on_status

- /message/order/fulfillments/end/time/timestamp should be provided range

## Common

- Flows should be in sequential order

@skdeep12

**Comment by sahil-ondc** [comment]
That was something that end/timestamp should be in the range which you have provided, like if range is (5PM -7PM) then timestamp should be between it, but as I have discussed with @bluecypher, you can ignore that for logs submission

@skdeep12

**Comment by sahil-ondc** [comment]
## Flow 1

### search_full_catalog_refresh

- /context/ttl should be PT30S

### on_search_full_catalog_refresh

- /message/catalog/bpp~1providers/0 must have required property 'fulfillments'
- /message/catalog/bpp~1providers/0/items/0 must have required property '@ondc/org/seller_pickup_return'
- /message/catalog/bpp~1providers/0/items/0 must have required property '@ondc/org/contact_details_consumer_care'
- /message/catalog/bpp~1providers/0/items/0/descriptor must have required property 'symbol'
- /message/catalog/bpp~1providers/0/items/0/quantity/available/count must be equal to one of the allowed values (99,0)

### search_inc_catalog_refresh

- transaction logs not provided

### on_search_inc_catalog_refresh

- transaction logs not provided

## Flow 2

### on_select

- /message/order/provider/id mismatches in /on_search and /on_select

### init

- /message/order/items/0 must have required property 'fulfillment_id'

### on_init

- /message/order must have required property 'tags'
- /message/order/items/0 must have required property 'quantity'
- context/timestamp should be in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format

### on_confirm

- /message/order must have required property 'tags'
- /message/order must have required property 'created_at'
- /message/order must have required property 'updated_at'
- /message/order/fulfillments/0 must have required property 'tracking'
- /message/order/payment must have required property 'params'
- store name /fulfillments[0]/start/location/descriptor/name should be same as provided in on_search
- fulfillments[0].end.location.address.area_code is not matching with area_code in /select

### on_status

- /message/order must have required property 'tags'
- /message/order must have required property 'created_at'
- /message/order must have required property 'updated_at'
- /message/order/fulfillments/0 must have required property 'tracking'
- /message/order/id should remain same as created in confirm request

## Flow 3

### on_select (out-of-stock)

- error object should be exactly as per the API contract

## Other flows

### on_cancel

- /message/order/tags should have required property 'quote_trail' as per the API contract

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full_catalog

- /message/catalog/bpp/descriptor/tags/bpp_terms must have property np_type (ISN, MSN)
- /message/catalog/bpp/providers/locations/address must have required property 'circle'
- /message/catalog/bpp/providers/items must have required property '@ondc/org/seller_pickup_return'
- /context/city should be as per the area_code provided in /message/catalog/bpp/providers/locations/address
- invalid field provided 'OndcError'
- /message/catalog/bpp/providers/categories should have unique ids
- /message/catalog/bpp/providers/items should have unique ids

### search_inc_refresh

- context/city should be '\*' while sending search_inc_catalog request
- /message/intent/tags/list/start_time/value cannot be greater than or equal to /context/timestamp
- /message/intent/tags/list/end_time/value cannot be greater than /context/timestamp

### on_search_inc_catalog

- bpp/fulfillments sent in payload shoulnd't be part of /on_search_inc_refresh api
- bpp/descriptor sent in payload shoulnd't be part of /on_search_inc_refresh api

## Other flows

### on_select

- available count can't be greater than maximum count for item id: 13899

### on_init

- /message/order must have required property 'tags'

### confirm

- /message/order/payment settlement_details mismatch in /on_init & /confirm

### on_confirm

- /message/order must have required property 'tags'
- provider_tax_number (pan number of merchant) should be provided in /tags/bpp_terms

## Flow 3

- Flow should be as per rollout sheet, after out of stock, flow should continue with the items which are in stock

## Note

- City code mismatch in /search and Another api endpoints

@skdeep12

**Comment by vashistavivek** [comment]
@sahil-ondc 
**on_search_full_catalog**
- /message/catalog/bpp/providers/locations/address must have required property 'circle'
it is not mentioned in the API doc that address have 'circle' property, we are sending 'circle' inside /message/catalog/bpp/providers/locations/0

**Comment by bluecypher** [comment]
**/search**

- tracking is not a valid attribute in /fulfillment
- key attribute is optional in /context;

**/on_search**

- exp is not a valid attribute
- bpp/categories is not required
- "accept_bap_terms" object is not required till static terms are enabled
- geocoding of store location is inaccurate; gps and area_code must match
- "@ondc/org/statutory_reqs_packaged_commodities" is missing for SKUs as per the category protocol key mapping

**/on_search (inc)**

- one-time inc callback response should not take long

**/on_select**

- millisecond value should be of 3 characters in context/timestamp
- quote/breakup line items with price=0 need not be provided; item and delivery charges are mandatory
- invalid attributes: "@ondc/org/returnable", "@ondc/org/cancellable", "@ondc/org/available_on_cod", "@ondc/org/seller_pickup_return" in /quote/breakup/item
- available quantity should be either "99" or "0" indicating the availability of stock in quote/breakup/item

**/init**

- why is there huge difference in created_at/updated_at from context/timestamp in /billing
- invalid gps and area_code in /billing and /fulfillments; addres is of Gurgaon but gps coordinates point to Bihar
- door is not a valid property in /billing and /fulfillments

**/on_init**

- static/dynamic terms need not be provided in /tags/bpp_terms till enabled; only GSTIN number should be provided in "tax_number";
- GSTIN number length in tax_number seems incorrect; pls check
- settlement details must be provided by SNP in /on_init for prepaid orders; otherwise payment object with type= ON-FULFILLMENT must be provided in /select call for CoD payment

**/confirm**

- "accept_bap_terms" object is not required till static terms are enabled
- tax_number (gstin of bap) is missing in /bap_terms
- attributes: transaction_id and transaction_status need not be provided in /payment/params

**/on_confirm**

- only tax_number, np_type and provider_tax_number should be provided in /tags/bpp_terms
- fulfillment TAT must be provided in /fulfillments/"@ondc/org/TAT"
- updated_at timestamp should be updated

**/on_status**

- order and fulfillment state mapping must be correct; order state can't be "Accepted" when fulfillment state is "Packed"; check this [section](https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.ii1xl1f08zho) in the contract
- label attribute is not required in /time
- invoice should only be provided when the order is picked and thereafter
- updated_at timestamp should be updated appropriately
- city code should be captured correctly; can't be "\*"
- Completed:
  - transaction_id must be provided in payment/params for PoD orders when order is Completed
  - time/timestamp must be provided in payment for PoD orders

## Flow 3

**/on_select**

- both the items must be a part of error object; since part/entire stock is unavailable
- /select must be reinitiated with same txn id in case of any change in the cart

## Flow 4

**/on_cancel**

- city code can't be "\*"
- message_id should be the same as in /cancel
- cancellation should not be allowed post shipment; cancellation terms must be enabled in order to allow post shipment cancellation
- precancel_state must be provided in /fulfillment/tags
- cancellation object is missing in /order

## Flow 5

**/on_cancel**

- precancel_state must be provided in /fulfillment/tags
- line items with value =0 need not be provided in quote_trail
- RTO must be initiated in /on_cancel and later disposed in /on_status

## Flow 6

- merchant part cancel flow is missing

**/update**

- "reason_description" is invalid; should be "reason_desc";
- value of "code": "images" is missing

**/on_update**

- value of code reason_desc can't be removed
- refund must be initiated once the fulfillment is Liquidated and refund related payment settlement details must be appended in /@ondc/org/settlement_details
- line items where the value is adjusted should only be provided in quote_trail; no need to provide line items where value = 0


@vashistavivek

**Comment by bluecypher** [comment]
**/on_search**

- variant grouping is created but single SKU is present for those groups
- seller must be of the same city for which search is initiated; search initiated for Patna city but the seller is located in UP
- address/state of the seller is not captured correctly; GPS and area code are of UP

**/on_search (inc)**

- provider 3456 is not a part of full catalog pull
- no incremental changes in the catalog; delta changes must be provided

**/select**

- payment object with type= ON-FULFILLMENT must be provided in /select call for CoD payment

**/on_select**

- quote/breakup line items with price=0 need not be provided; item(s) and delivery charges are mandatory though
- fulfillment id is same as the fulfillment id for the types of fulfillment in /on_search; How are multiple fulfillment supported?

**/on_confirm**

- bap_terms are missing in /tags; should be the same as provided in /confirm
- address details of merchant should not change in /fulfillments/start/location; should remain the same as in /on_search

**/on_status**

- order state: "Accepted" and fulfillment state: "Out-for-delivery" are missing
- order/created_at timestamp should not change; must remain the same as in /confirm
- invoice link is not accessible

- Completed:
  - payment status should be "PAID"

## Flow 4

**/on_cancel**

- why are delivery charges still present even when the order is cancelled before shipment

## Flow 5

**/on_cancel**

- invalid city code;
- invalid attributes "@ondc/org/returnable", "@ondc/org/cancellable", "@ondc/org/available_on_cod", "@ondc/org/seller_pickup_return" in /quote/breakup/item
- RTO must be initiated in /on_cancel and later disposed in /on_status
- precancel_state must be provided in /fulfillment/tags
- line items with value =0 need not be provided in quote_trail, only the adjusted prices should be present; This is applicable for quote_trail in all the APIs
- order/updated_at should be updated as per the changes in order/fulfillment object

## Flow 6

- /on_update call for merchant part cancel is missing

**/update**

- value of images should be in url format

**/on_update**

- refund must be initiated once the fulfillment is Liquidated and refund related payment settlement details must be appended in /@ondc/org/settlement_details
- line items where the value is adjusted should only be provided in quote_trail; no need to provide line items where value = 0


@vashistavivek

**Comment by sandeepshahi** [comment]
**/on_search**

- new construct of store timings must be provided in /bpp/providers/tags/timing

**/on_select**

- quote/breakup line items with price=0 need not be provided; item(s) and delivery charges are mandatory though
- fulfillment id is same as the fulfillment id for the types of fulfillment in /on_search; How are multiple fulfillment supported?
- available count should be either 99 or 0 indicating the availability of inventory

**/on_init**

- payment related info must be provided in /payment (type, status, settlement_basis, settlement_window, withholding_amount) for PoD payments

**/on_status**

- Agent-assigned, Out-for-Delivery

  - message_id should be unique
  - updated_at should be updated; can't be the same as in the previous state

## Flow 4

**/on_cancel**

- message_id should be the same as in /cancel
- delivery charges should also be adjusted in quote_trail if quote/breakup price for delivery=0;

## Flow 5

**/on_cancel**

- invalid reason code "017"; should be a valid RTO triggering reason code; refer to the mapping [here](https://docs.google.com/spreadsheets/d/1_qAtG6Bu2we3AP6OpXr4GVP3X-32v2xNRNSYQhhR6kA/edit#gid=1095388031)
- rto reason id mismatches in order/fulfillments/cancel_request and order/cancellation
- precancel_state is not captured correctly
- rto delivery price is 0; line items with value =0 need not be provided in quote_trail, only the adjusted prices should be present; This is applicable for quote_trail in all the APIs
- adjusted forward delivery charges must be present in quote_trail; since quote price is 0;
- RTO is initiated through "5009-RTO"; why is fulfillment object "5009-Cancellation" created?

## Flow 6

**/on_update**

- line items where the value is adjusted should only be provided in quote_trail; no need to provide line items where value = 0

**/on_status (reject/liquidated)**

- /on_update call must be used; since there is change in order object (quote, items, fulfillments)


@vashistavivek

**Comment by sandeepshahi** [comment]
## Flow 2

**/select**

- geocoding of gps and area_code seems inaccurate;

## Flow 5

**/on_cancel**

- "updated_at" timestamp of precancel_state is not captured correctly; should be of Out-for-delivery state

## Flow 6

**/on_update**

- line items where the value is adjusted should only be provided in quote_trail; no need to provide line items where value = 0; (mandatory*)


@vashistavivek

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search (full catalog):
- item 15720: pls remove formatting in long_desc; also the hindi letters are encoded as UTF-8 literals?

**Comment by BLR-0118** [comment]
Flow 2
====
1. /on_init:
- payment.collected_by should be added;

2. /confirm:
- what does Context.key here mean? (not in any other APIs)

3. all pre-order callbacks: fulfillment.tracking missing;
4. can you also add routing.type to indicate hyperlocal (P2P) or intercity (P2H2P) shipment;

Flow 3
====
1. Context.timestamp for 2.1.select is earlier than 1.2.on.select; how does 2.1.select know which items are in-stock when it's timestamp is earlier than the previous response?

Flow 5
====
1. time for RTO initiation & delivered/disposed needs to be provided (for RTO fulfillment);
2. curious why you're using RTO-disposed for such high value items that have resaleable value;

**Comment by BLR-0118** [comment]
Flow 6
====
1. 7.0.on_update(merchant_part_cancel):
- quote_trail should only have any quote line item with delta changes (thus, tax shouldn't be here);

2. No return with pickup?

**Comment by BLR-0118** [comment]
also, since discount is 0 you may want to remove it from quote.breakup[]

**Comment by BLR-0118** [comment]
@vashistavivek - pls fix above & resubmit for flow 3 only;

**Comment by vashistavivek** [comment]
@skdeep12 FYI

**Comment by BLR-0118** [comment]
Point 4 raised above for flow 2 not addressed, pls fix;

@vashistavivek - clearing logs for v1.2.0 (AGR10), pls make sure above issue is addressed;

**Comment by vashistavivek** [comment]
@BLR-0118 I will fix it today, thanks!

**Comment by BLR-0118** [comment]
Hi @vashistavivek - can you pls share a demo of your buyer app? Wanted to check the UX

**Comment by vashistavivek** [comment]
@BLR-0118 
You can download our internal-debug-app from here: https://drive.google.com/drive/folders/1A-v9JGob-1icz3U2GDp5kPYtorv39wpQ

testing provider location -> sampatchak, bihar
Provider name -> M/S New Rakesh Beej Bhandar

steps:
1. hamburger(right-top) -> "Shop via ONDC"
