### ISSUE TITLE
eSamudaay (RET10) - compliance check

### ISSUE THREAD

**Issue by BLR-0118** [ONDC-Official/v1.2.0-logs#648]
Flow 1
====
1. /on_search:
- item.quantity.unitized.measure is showing in units for everything; this is ok for F&B but in grocery, you need the proper units like gram / kilogram / millilitre /litre / etc as per the list [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json);
- for custom menu (bpp/providers.categories), short_desc & long_desc need to be provided;
- remove "accept_bap_terms" until static terms are enabled;

2. /on_search_inc:
- includes invalid parent_item_id (15997);
- pls share logs for common grocery use-cases like item out of stock / price change;

Flow 2
====
1. /on_confirm:
- request to also send provider_tax_number for buyer NP to verify MSN/ISN;

2. /on_status APIs:
- there's no fulfillment.provider_id in /on_confirm but it appears in /on_status?
- since fulfillment.tracking is "false" in /on_confirm, you don't need to set the flags for tracking (gps_enabled / url_enabled / url);

3. /on_track:
- fulfillment.tracking is false in /on_confirm, means tracking isn't available; how can /on_track return gps coords? Instead, the behaviour should be as per contract;

**Comment by BLR-0118** [comment]
@Namratha102000 - pls fix & resubmit logs for flow 1 & 2 only

**Comment by Namratha102000** [comment]
### Flow 1

**/on_search:**

item.quantity.unitized.measure is showing in units for everything; this is ok for F&B but in grocery, you need the proper units like gram / kilogram / millilitre /litre / etc as per the list [here](https://github.com/ONDC-Official/protocol-network-extension/blob/main/enums/retail/uom.json); **--- FIXED (its mixture of gram,kilogram and unit)**
or custom menu (bpp/providers.categories), short_desc & long_desc need to be provided;**--Fixed**
remove "accept_bap_terms" until static terms are enabled **-- Fixed**

**/on_search_inc:**

includes invalid parent_item_id (15997); **--Fixed** 
pls share logs for common grocery use-cases like item out of stock / price change; **--FIXED (shared for price change)**

### Flow 2

**/on_confirm:**

request to also send provider_tax_number for buyer NP to verify MSN/ISN; **--Fixed**

**/on_status APIs:**

there's no fulfillment.provider_id in /on_confirm but it appears in /on_status? **--Fixed**
since fulfillment.tracking is "false" in /on_confirm, you don't need to set the flags for tracking (gps_enabled / url_enabled / url); **-- Fixed**
 **/on_track:**
fulfillment.tracking is false in /on_confirm, means tracking isn't available; how can /on_track return gps coords? Instead, the behaviour should be as per contract;**-- Fixed (Business delivery configurations was improper fixed)**

**Comment by Namratha102000** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/672 Please merge this new PR in previous one I forgot to update the incremental search requests

**Comment by Namratha102000** [comment]
@BLR-0118 Please review this

**Comment by BLR-0118** [comment]
1. /on_search:
- item 21290 - is this pineapple or pineapple juice? If latter, unitized qty should be in millilitre/litre;
- shouldn't category_id for item 23335, 23336 be "Masala & Seasoning"?
- variant group 17416 defined, but not linked to individual items?

2. /on_search_inc:
- item 21288 has price.value > price.maximum_value;
- it seems the entire item definition is being changed (from Musambi to Musambi Juice); in these cases, it normally comes with new SKU;

**Comment by BLR-0118** [comment]
@Namratha102000 - clearing logs for v1.2.0 (RET10), subject to above issues being fixed before deployment

**Comment by Namratha102000** [comment]
fixed
