### ISSUE TITLE
nStore (SA) - compliance check

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#656]
### search_full_catalog_refresh

- /message/intent/payment/@org/buyer_app_finder_fee_amount must be string

### on_search_full_catalog_refresh

- /message/catalog/bpp/providers/items/4/tags/1/list/0 must be object
- /message/catalog/bpp/providers/items/descriptor/code should be as per the API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yr8id0fwawkv`
- - /message/catalog/bpp/providers/0/items/0/quantity/unitized/measure/unit must be small case

### search_inc_refresh

- context/city should be "\*" while sending search_inc_catalog request

### on_search_inc_refresh

- /message/catalog/bpp/providers/0/items/0/quantity/unitized/measure/unit must be equal to one of the allowed values (unit,dozen,gram,kilogram,tonne,litre,millilitre)

### select

- /message/order/fulfillments/0/end/location/address/area_code must be string

### on_select

- quote.breakup.item.quantity. maximum should be (99,0)
- quote.breakup.item.quantity. available should be (99,0)
- message/order/fulfillments/state/descriptor name should not be included
- /message/order/fulfillments/0/end/location/address/area_code must be string

### init

- /message/order/billing/address/area_code must be string
- /message/order/billing/phone must be string
- /message/order/fulfillments/0/end/contact/phone must be string

### on_init

- provider_location should not be provided in /message/order (deprecated)
- message/order/ not according to api contract as cancellationTerms is included
- address.area_code in fulfillments[0].end.location mismatch in /select & /on_init
- Payment Object can't be null in /on_init
- Key 'price.value' mismatch: 711.00 !== 811.00

### confirm

- /message/order/billing/address/area_code must be string
- /message/order/billing/phone must be string

### on_confirm

- message/order/fulfillments/state/descriptor name should not be included according to api contract
- message/order/items/tags are not according to api contract
- /message/order/quote/price/value must be string
- Key 'price.value' mismatch: 711.00 !== 811

### on_status

- /context must have required property 'ttl'
- /message/order must have required property 'payment’
- /message/order/fulfillments/0 must have required property 'tracking'
- /message/order/fulfillments/0 must have required property '@ondc/org/TAT
- /message/order/fulfillments/0/start/instructions must have required property 'short_desc'

### on_select (out-of-stock)

- error object should be exactly as per the api contract

`https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl`

### on_cancel

- /message/order/tags should have 'quote_trail' as per the API contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yzl8pn3ixxec`

## Note

- Kindly submit Flow 5 as per the sheet

`https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795`

@nstoretech

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full_catalog_refresh

- 'accept_bap_terms' code should not be provided. It should be enabled when static terms are defined by the BNP and accepted by the seller app
- /message/catalog/bpp/providers/categories/tags/attr should hava value as 'item.quantity.unitized.measure', as variants are created on it
- /message/catalog/bpp/providers/items must have property '@ondc/org/statutory_reqs_prepackaged_food' as per the sheet
  `https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0`
- if variant_group is provided it should be mapped to one of the items for the variants
- id and parent_item_id cannot be same in /message/catalog/bpp/providers/items
- invalid attribute 'Quantity' provided in /message/catalog/bpp/providers/items/tags

### search_inc_refresh

- transaction logs not provided

### on_search_inc_refresh

- transaction logs not provided

## Flow 2

### select

- buyer selects multiple items (> 1 qty for each item) for checkout as per the roll out plan
  `https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795`

### on_init

- only tax_number should be provided in tags/bpp_terms; remove all the terms related properties
- provider_location object is deprecated; use provider/locations[] instead
- cancellation_terms should not be provided; static/dynamic terms need not be provided as part of phase 1

### on_confirm

- provider_tax_number (pan number of merchant) should be provided in /tags/bpp_terms
- only tax_number and provider_tax_number should be provided in /tags/bpp_terms; remove other terms related properties
- cancellation_terms should not be provided; static/dynamic terms need not be provided as part of phase 1

### on_status

- context/message_id cannot be same for on_status.delivered and on_status.picked and on_status.pending
- only tax_number and provider_tax_number should be provided in /tags/bpp_terms; remove other terms related properties

## Flow 3

### select (out-of-stock)

- multiple items should be selected and flow should continue with the item which is in stock

## Other Flows

- same as above flows

@nstoretech

**Comment by arunraj-nstore** [comment]
provider_tax_number is required only if np_type is 'ISN' as per the document. Is it required to add it in the payload though we are MSN.

**Comment by sahil-ondc** [comment]
## Flow 1

### on_search_full_catalog

- 'brand_owner_FSSAI_license_no', 'importer_FSSAI_license_no' should not be provided as empty string "" in /message/catalog/bpp/providers/items/@ondc/org/statutory_reqs_prepackaged_food
- short_desc and long_desc should not be provided as empty string "" in /message/catalog/bpp/providers/items/descriptor
- invalid value 'item.tags.attribute.Quantity' provided in /message/catalog/bpp/providers/categories/tags/attr
- /message/catalog/bpp/providers/categories/tags/attr should hava value as 'item.quantity.unitized.measure', as variants are created on it
- invalid attribute 'Quantity' provided in /message/catalog/bpp/providers/items/tags

### on_search_inc

- same issues as above in on_search_full_catalog

## Flow 3

### on_select (out-of-stock)

- multiple issues please check API contract for out-of-stock
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.c6o4dr7q1ywl`

## Flow 4

### on_cancel

- cancelled_by should be buyer application bap_id

## Flow 5

### on_cancel

- Transactional log is not as per contract
  `https://docs.google.com/document/d/1brvcltG_DagZ3kGr1ZZQk4hG4tze3zvcxmGV4NMTzr8/edit#heading=h.yzl8pn3ixxec`

## Other flows

### on_select

- /message/order/provider must have required property 'locations'
- /message/order/quote/breakup/[0]/quantity 'available' and 'maximum' logic should remain same as provided in on_search_full_catalog

### on_init

- 'provider_tax_number' should not be part of the /message/order/tags/bpp_terms in on_init

@nstoretech

**Comment by arunraj-nstore** [comment]
We managed the UOM (unit of measure) as a part of the product attribute in our system to make the product extensively configurable. So that we used 'item.attribute.Quantity' for making a variant group instead of 'item.unitized.measure' to avoid hardcoding of UOMs in our product...So we are sending the uom as single unit and the variant values under respective product attributes. This way we will be compliant with ONDC specs without hardcoding UOM and also don't need to change our product...We are happy to discuss this over a call and sort out if needed.

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search (full catalog):
- use proper unitized qty e.g. item 100 should have unitized qty of 500 gram instead of 1 unit;
- item.tags.attribute.quantity is invalid: pls use only the attributes listed [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0);
- day_from can't be greater than day_to;
- use meaningful buyer-readable name for variant "V2" instead of "Variant Group 2";

2. /on_search (incr):
- not sure what's changed for item 100 for it to be a part of incremental update (common use cases like item being out of / in inventory, price change is not shown);

Flow 2
====
1. /on_select:
- TAT of 0 days for F2 isn't correct (should be < 1 hr if F1 is for 1 hr);
- remove quote.type until enabled;

2. /on_init:
- pls add fulfillment TAT;

3. /on_confirm:
- provider_tax_number should be PAN no;

4. /on_status (accepted):
- invoice should be added at Order-picked-up;

5. All fulfillment states to be provided (including Agent-assigned, Out-for-delivery);

Flow 3
====
1. /on_select (out of stock):
- error.message format is invalid;

Flow 4
====
1. /on_cancel:
- cancel_request should be for F1;
- pls add precancel_state;

Flow 5
====
1. /on_cancel:
- quote.breakup[] is invalid: e.g. for item 115, unit price (126) * qty (0) shows total price of 40.50??
- quote_trail is invalid because of the above;
- all other issues for flow 4 apply here;

Flow 6a
=====
1. /on_update:
- part cancel initiated by merchant; reason code & cancelled by are both invalid;

Flow 6b,c
======
1. /on_update:
- fulfillment id for return request is wrong (has to match return request id);
- entire return request should be shown in the return fulfillment (return initiated);
- quote_trail missing in return liquidated;

2. pls also share log for return pickup failure, leading to return failure;

**Comment by BLR-0118** [comment]
@arunraj-nstore @nstoretech

**Comment by arunraj-nstore** [comment]
@BLR-0118 Please help us to get clarification on the following items.

on_init: pls add fulfillment TAT - As per the document it is added in on_confirm. Should I need to add it on_init.
on_cancel: pls add precancel_state - As per the document, it is an optional parameter. Is it required to be added.

**Comment by BLR-0118** [comment]
@arunraj-nstore - whatever's been requested needs to be taken care of

**Comment by BLR-0118** [comment]
Group A
======
1. /on_search (full catalog):
- all products shown are branded, surprising there's no EAN no?
- you may want to use the optional attribute "brand" for these branded items;
2. /on_confirm:
- start & end time slot are same (11:56-12:16);
- if start time slot is 11:56-12:16 & since TAT is 1 hr, shouldn't end slot be 12:56-13:16?
3. for flow 2 hyperlocal, pls add routing.type=P2P & send all statuses (Agent-assigned, Packed are missing);

Group B
=====
1. Flow 5 is specifically for RTO, i.e. when order has left the seller premises & may have to be returned back; there are additional attrs in cancel_request which need to be added;

Group C (flow 7)
===========
1. return_1_initiated:
- /on_update for return initiated is a solicited response, should have same message_id as return request;
- what does the start timeslot for return fulfillment indicate?
2. return_1_liquidated:
- what does start.location for return fulfillment mean in this case?
3. return_2_approved:
- pickup location should actually be the buyer address, not store address;
4. return_2_picked:
- items[] is wrong as all count for item 100 is assigned to fulfillment F1;

pls resubmit for flow 6b & c (return with liquidation, return with pickup) where all the other issues (above) can be checked;

**Comment by BLR-0118** [comment]
@arunraj-nstore

**Comment by arunraj-nstore** [comment]
Hi Supriyo,

We have re-submitted the logs for flow 6b&c as requested. Please review.


https://github.com/ONDC-Official/v1.2.0-logs/pull/1068

Thanks
Arunraj Selvam

**Comment by BLR-0118** [comment]
@arunraj-nstore - point 3 for Group A above not yet handled. Pls have it fixed & update here. No need to resubmit logs

**Comment by arunraj-nstore** [comment]
@BLR-0118 

We have updated the routing.type and packed state. Here is the payload link for your reference.   [](http://jsonblob.com/1219555085033267200)

We are currently not supporting the "Agent-Assigned" status and we will definitely work on this post we go live with V1.2. Thank you

**Comment by BLR-0118** [comment]
logs cleared for v1.2.0 (RET10), subject to caveat above;
