### ISSUE TITLE
Nivea (SA) IGM - compliance check

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#662]
@Schbang-parmeshwar 

 Flow 1:
issue :
-  "updated_at": "The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in issue"

on_issue_status
- "igmIssueMsgId": "Message  ID mismatch in /issue_status and /on_issue_status

**Comment by Schbang-parmeshwar** [comment]
@RupalSingla please correct me if i am wrong here
Flow 1:
issue :

- "updated_at": "The 'updated_at' of message/issue/issue_action/complainant_actions/index[0]/updated_at should be the same as or less than 'message/issue/update_at' in issue"
###  this issue is from buyer-ref-app

on_issue_status

- "igmIssueMsgId": "Message ID mismatch in /issue_status and /on_issue_status
### message id would be different in case its un_solicilated on_status from BPP

**Comment by Rishabh-ondc** [comment]
Logs cleared

@Schbang-parmeshwar

**Comment by Schbang-parmeshwar** [comment]
@RupalSingla  please close this issue

cc: @bluecypher

**Comment by RupalSingla** [comment]
Logs  cleared  for IGM @Schbang-parmeshwar
