### ISSUE TITLE
Dailybee (SA: RET10) - compliance checks

### ISSUE THREAD

**Issue by sahil-ondc** [ONDC-Official/v1.2.0-logs#803]
# RET10

### on_search_full_catalog

- 'accept_bap_terms' code should not be provided. It should be enabled when static terms are defined by the BNP and accepted by the seller app
- deprecated category ids should be avoided in /items/category_id; will be removed moved to different category over a period of time
- /message/catalog/bpp/providers/items should not have property 'category_ids'

### on_search_inc_catalog

- /message/catalog/bpp/providers should not have property 'categories' if already sent in full_catalog_refresh

### on_select

- /message/order/quote/breakup/item/quantity available and maximum should be same as provided in 'on_search'

### on_init

- /message/order should not have property 'provider_location' (deprecated)
- /message/order/payment/@ondc/org/settlement_basis should have value one of the 'delivery' (from delivery), 'shipment' (from shipment), 'return_window_expiry' (from expiry of return window);
- invalid uri provded in /message/order/payment

### on_confirm

- provider_tax_number (pan number of merchant) should be provided in /tags/bpp_terms

### on_status (delivered)

- /message/order/fulfillment/end/time/range/end should be same as provided in previous on_status calls

@a-satyateja

**Comment by nishthamongaondc** [comment]
## Flow 1

### on_search_full_catalog_refresh
- /message/catalog/bpp~1providers/0/items/0/descriptor/code item/descriptor/code should be in this format - \"type:code\" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others
- Invalid category ID in /message/catalog/bpp~1providers/0/items/0/category_id 
- Time must be RFC3339 UTC timestamp format in /message/catalog/bpp~1providers/0/tags/1/list/3/value.

## Flow 2

### on_status_packed
- pickup timestamp should match context/timestamp and can't be future dated
- order/updated_at timestamp can't be less than the pickup time

@a-satyateja

**Comment by a-satyateja** [comment]
@sahil-ondc 
@nishthamongaondc 

# Flow 1

I have updated the logs for flow 1 addressing the below comments. 
[x]  - ~/message/catalog/bpp 1providers/0/items/0/descriptor/code item/descriptor/code should be in this format - "type:code" where type is 1 - EAN, 2 - ISBN, 3 - GTIN, 4 - HSN, 5 - others~
[x] - ~Time must be RFC3339 UTC timestamp format in /message/catalog/bpp~1providers/0/tags/1/list/3/value.~

The third comment is not valid, "Rice and Rice Products" is a valid category_id according to this document. 
https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=0
[ ] - Invalid category ID in /message/catalog/bpp~1providers/0/items/0/category_id


# Flow 2
The below comment is invalid since on packed event we do not have the timestamp for pickup, please check again. 

on_status_packed
[] - pickup timestamp should match context/timestamp and can't be future dated
order/updated_at timestamp can't be less than the pickup time

**Comment by a-satyateja** [comment]
@sahil-ondc 
@nishthamongaondc 


Please address the comments.

**Comment by NishthaMonga** [comment]
## Flow 1
### on_search_full_catalog_refresh
- /message/catalog/bpp~1providers/0/tags/1/list/3/value Time must be RFC3339 UTC timestamp format.
- Timestamp not in RFC 3339 (YYYY-MM-DDTHH:MN:SS.MSSZ) Format


@a-satyateja

**Comment by a-satyateja** [comment]
@NishthaMonga 
@sandeepshahi 

Please verify the latest logs submitted @ https://github.com/ONDC-Official/v1.2.0-logs/pull/1067

**Comment by sandeepshahi** [comment]
### remove all the unnecessary folders and submit only the latest logs

## Flow 1

**/on_search**

- store timing must be provided as per the new construct in /bpp/providers/tags/timing
- why is the seq of the single attribute in variant group v1 set as "2"; It should be 1 instead
- white spaces must be avoided in string values; check maximum_value price of items
- fssai license no in "@ondc/org/fssai_license_no" need not be provided for packaged commodities
- value of statutory reqs can't be "NA"

**/on_search (inc)**

- message_id for unsolicited calls must be unique; mode = "start" is regular incremental pull and message_id for all the subsequent delta changes in /on_search need not be the same
- invalid value of code in /items/descriptor; should be in the correct format as mentioned in the contract

## Flow 2

**/on_select**

- avoid creating long fulfillment and store location ids; might not be accepted by BNPs
- "locations" is missing in /provider

**/on_init**

- type, collected_by, uri (payment link), status, settlement_basis, settlement_window, withholding_amount should only be provided if payment is collected by SNP

**/on_confirm**

- many invalid attributes in /start; check contract for the required attributes;
- How can the store address be changed in /start/location/address even though the GPS is the same as in /on_search?
- estimated pickup and delivery time ranges are not in conformance with the TAT; delivery TAT is mentioned as 1 hour and 12 minutes whereas estimated time ranges are of 2 hours
- provider/locations is missing
- np_type must also be provided in /tags/bpp_terms

**/on_status**

- invoice link is inaccessible
- "Agent-assigned" and "Out-for-delivery" states are missing

**/track**

- tracking must be supported if tracking is set as "true"

## Flow 3

- similar issues as above

## Flow 4

- similar issues as above

**/cancel**

- inaccurate reason code "006" used, should only be used in case of TAT breach; SNP must respond with a NACK

**/on_cancel**

- invalid schema; items/quantity/count should be in integer format
- "@ondc/org/provider_name" can't change in /fulfillments
- incorrect quote calculation; quantity of items should also be 0 since: unit price \* count = total price

## Flow 5

- similar issues as above

**/on_cancel, /on_status (RTO)**

- similar issues as above
- only the adjusted price should be included in quote_trail; delivery charges are not adjusted therefore won't be part of quote_trail
- RTO delivery timestamp should be provided in /on_status in /fulfillments/end/time/timestamp

## Flow 6

- similar issues as above

**/on_update (Liquidated)**

- quote_trail must be provided for liquidated item

**/update (FYI)**

- refund related FYI call must be accepted by SNP


@a-satyateja

**Comment by sandeepshahi** [comment]
@a-satyateja, precancel_state must be provided in case of cancellation (part/fulll)

**Comment by a-satyateja** [comment]
@sandeepshahi 
@NishthaMonga 

Please verify the latest logs submitted @ https://github.com/ONDC-Official/v1.2.0-logs/pull/1241

**Comment by BLR-0118** [comment]
Flow 1
====
1. /on_search_full_catalog_refresh:
- Context.domain should be "ONDC:RET10", not "ONDC:RET18";
- for all items, price.maximum_value is invalid (has space at end);
- why is EAN code not being used for items (is it because these are not branded items)?
- curious why returnable is true for all items but seller_pickup_return false?

Flow 2
====
1. /on_track:
- pls send the complete payload as per the contract;

2. /on_status:
- in order to help buyer apps to distinguish between status for hyperlocal / intercity orders, pls set routing.type to "P2P" (hyperlocal) or "P2H2P" (intercity) - this can be set when the order is accepted;
- to optimize track processing by buyer apps, pls set gps_enabled to "yes" (when tracking for the fulfillment has been enabled);

Flow 3
====
1. /on_select (with error):
- 40002 (error no) should also be within escaped double quotes;

Flow 5
====
1. /on_cancel_RTO_init:
- quote_trail should only have differential line items; thus, id "SD_PL_65b7a8a9ee15576c92ed0725" with value of 100 need no be here as it's already a part of quote;
- if you want to add RTO charge, you can have quote_trail with id "RTO1" with value having the corresponding cost;
- pls also add start & end locations for the "Cancel" fulfillment (only for fulfillment.type "RTO") as some buyer apps are validating this;

**Comment by BLR-0118** [comment]
@a-satyateja - pls fix the issues above (1st 2 points of point 1 on priority);
Clearing logs for v1.2.0 (RET10), pls make sure the above are fixed ASAP

**Comment by a-satyateja** [comment]
@BLR-0118 

# Flow 1
/on_search_full_catalog_refresh:
✅  _Context.domain should be "ONDC:RET10", not "ONDC:RET18";_
for all items, price.maximum_value is invalid (has space at end);
✅  _why is EAN code not being used for items (is it because these are not branded items)?_ -- These are lose-packed items from the store, hence non-branded. 
✅  _curious why returnable is true for all items but seller_pickup_return false?_ -- Fixed this. 

# Flow 2
/on_track:
✅ pls send the complete payload as per the contract; -- Fixed this.
