### ISSUE TITLE
Bitsila - compliance check

### ISSUE THREAD

**Issue by sharmasahil0331** [ONDC-Official/v1.2.0-logs#84]
**on_search_full_catalog_refresh**

- /message/catalog/bpp~1providers/fulfillments/contact/email must match format \"email\"
- /message/catalog/bpp~1providers/locations/time must have required property 'label'
- /message/catalog/bpp~1providers/locations/time must have required property 'timestamp'
- @ondc/org/contact_details_consumer_care should be in the format \"name,email,contactno\" in /bpp/providers/items
- duplicate seq in category_ids in /message/catalog/provider/item
- value passed in serviceability tags should be same as passed in location/circle
- category in serviceability construct should be one of the category ids bpp/providers[0]/items/category_id

**search_inc_refresh**

- context/city should be '*' while sending search_inc_catalog request
- /message/intent/tags/list/end_time/value cannot be greater than /context/timestamp

**on_search_inc_refresh**

- /message/catalog/bpp~1providers/0/items/0/descriptor/short_desc cannot be null it must be string
- /message/catalog/bpp~1providers/0/items/0/descriptor/long_desc cannot be null it must be string
- /message/catalog/bpp~1providers/0/items/0/quantity/unitized/measure/unit must be equal to one of the allowed values (unit,dozen,gram,kilogram,tonne,litre,millilitre)

**confirm**

- /message/order must have required property 'tags'
- payment settlement_details mismatch in /on_init & /confirm

**on_confirm**

- /message/order must have required property 'tags'
- /message/order/fulfillments/start/location must have required property 'address'
- /message/order/fulfillments/start/contact/email must match format "email"
- store name /fulfillments/start/location/descriptor/name can't change

**on_status**

- /message/order/payment/@ondc/org/settlement_details must have required property 'settlement_timestamp'
- /message/order/billing/address must have required property 'building'
- /message/order/fulfillments/start must have required property 'time'
- /message/order/fulfillments/start must have required property 'contact'
- /message/order/fulfillments/start/location/address must have required property 'state'

**common**

- /message/order/quote must have required property 'ttl'
- /message/order/payment must have required property '@ondc/org/settlement_basis'
- /message/order/payment must have required property '@ondc/org/settlement_window'
- /message/order/payment must have required property '@ondc/org/withholding_amount'

**Comment by bluecypher** [comment]
@dgowda604

**Comment by dgowda604** [comment]
@bluecypher  we have resubmitted logs based on the review. Please review the changes in this pull request: https://github.com/ONDC-Official/v1.2.0-logs/pull/94

Additionally, there are a few clarifications regarding the previous comments:

1. Regarding the comment on `message/order/payment/@ondc/org/settlement_details`: The property 'settlement_timestamp', We will only send this information if the amount is settled, as all the order buyer apps are settling later.

2. Concerning the comment on 'message/order/fulfillments/start': We will only send this information if the order is in a state such as picked up, out for delivery, etc. This information is provided by our on-network logistics. During the 'accepted' state, this time range is not sent from logistics.

We have  made changes only for seller API calls.

**Comment by sharmasahil0331** [comment]
**search_inc_catalog**

- search_inc_catalog transaction logs not submitted

**on_search_full_catalog_refresh**

- message/catalog/bpp/providers/0/@ondc/org/fssai_license_no must be string
- store enable/disable timestamp (/bpp/providers/time/timestamp) should be less then or equal to context.timestamp
- duplicate seq_id found in items/category_ids

**on_init**

- Discrepancies between the quote object in /on_select and /on_init, Delivery charges for FPO:1548:1:165288 are present in on_select but not in on_init

**on_confirm**

- Discrepancies between the quote object in /on_select and /on_confirm, Delivery charges for FPO:1548:1:165288 are present in on_select but not in on_confirm

**on_status**

- /message/order/fulfillments/0 must have required property '@ondc/org/TAT'
- /message/order/fulfillments/0/start must have required property 'time'
- /message/order/fulfillments/0/end must have required property 'time'

**common**

- /message/order/quote must have required property 'ttl'

@dgowda604

**Comment by dgowda604** [comment]
https://github.com/ONDC-Official/v1.2.0-logs/pull/99


search_inc_catalog: 

We are conducting tests with the Pincode feature, and it will only handle the pull operation, not the push. Therefore, we submitted only the push, as you indicated to expect context.city as *. This will apply across different cities and providers and will be sent to the buyer apps.



Regarding on_search_full_catalog_refresh

I couldn't find any duplicate sequence numbers here. Please revalidate once again, and if any are identified, kindly share the duplicate sequence IDs



Regarding on_init & on_confirm quote, here are few clarifications:

The understanding is that within the on_select function, we will provide self-pickup and delivery options for order fulfillments. Buyer applications will choose between delivery or pickup and initiate a init call. Therefore, the on_select function will encompass both options. In the on_init function, there will be the revised quote, indicating either delivery or pickup.



Regarding on_status

/message/order/fulfillments/0/end will be present when the order is marked as out-for-delivery. If the order is in a pending or packed state, this data will not be available. This interpretation aligns with the protocol as I understand it.



We have re-submitted the logs through this PR: https://github.com/ONDC-Official/v1.2.0-logs/pull/99

Please reevaluate once again."=

**Comment by BLR-0118** [comment]
@bluecypher - as discussed, pls address the above

**Comment by bluecypher** [comment]
**/inc_search**

- incremental search should be initiated by the BNP

**/on_search**

- context/timestamp can't be the same as /search timestamp
- store enable/disable timestamp (/bpp/providers/time/timestamp) can't be future dated
- "Delivery and Self-Pickup" is not a valid fulfillment type; separate fulfillment object should be created for each type and default fulfillment type should be provided in bpp/providers/items/fulfillment_id
- category should be provided in string format instead of unicode sequence format
- bpp/providers/fulfillments/contact/email should be in correct email format
- preferred display sequence is set as "0" for multiple custom menus;
- "@ondc/org/statutory_reqs_packaged_commodities","@ondc/org/statutory_reqs_prepackaged_food" & "@ondc/org/mandatory_reqs_veggies_fruits" are optional for F&B categories
- parent and child custom groups can't have the same sequence eg: for item id: CG:111252: parent and child custom groups C:7503 and C:7505 have seq=1

**/on_select**

- count is not a valid attribute in quote/breakup/item

**/on_confirm**

- unit price of item: "1254042" can't change in quote/breakup/item

**/on_status**

- Order-picked-up state is missing
- invoice url should not change in the subsequent calls

### Flow 3 (OOS Scenario) is missing


@dgowda604

**Comment by dgowda604** [comment]
@bluecypher Submitted logs through this PR -> https://github.com/ONDC-Official/v1.2.0-logs/pull/108

As per the discussion, inc_search is tested with pincode, and the pull request specifically addresses start & end time along with city specifics. Consequently, we are responding with the same city, and for that interval,

The data refarding "@ondc/org/statutory_reqs_packaged_commodities," "@ondc/org/statutory_reqs_prepackaged_food," and "@ondc/org/mandatory_reqs_veggies_fruits" is being sent on preprod by default. This is necessary to test these attributes on buyer apps.

The 'Order-picked-up' state is missing -> This status is not triggered from the LSP dashboard; hence, we could not send this to buyer apps. If LSPs are sending 'order-picked-up,' then we are also relaying this information to buyer apps

**Comment by bluecypher** [comment]
**/on_search**

- callback response should not take longer (taking ~4hours)
- appropriate category_id should be used to define serviceability for grocery/electronics; + multiple categories won't be required in case of specific RET domain 
- Men's Fashion is not a valid category_id; Please refer to the document [here](https://docs.google.com/spreadsheets/d/1APAvavF_BNbTA89benAlGtv0GuFvpn2b6XXi4lSdTTw/edit#gid=1130527843)
- Self-Pickup option should be provided in /fulfillments (since fulfillment type is available in /on_select)

**/on_select (OOS)**

- /error/message should be in JSON stringified format as mentioned in the contract


@dgowda604

**Comment by dgowda604** [comment]
@bluecypher submitted logs for OOS -> https://github.com/ONDC-Official/v1.2.0-logs/pull/111

**Comment by bluecypher** [comment]
/on_select (OOS)
- Invalid format of error/message; for customizations dynamic_item_id,customization_id & customization_group_id should be provided

@dgowda604

**Comment by bluecypher** [comment]
@BLR-0118, the seller app v1.2 logs seem fine. Please proceed with your review.

@dgowda604

**Comment by BLR-0118** [comment]
1. /on_search:
- grocery keys being sent for f&b - statutory_reqs_packaged_commodities, statutory_reqs_prepackaged_food, mandatory_reqs_veggies_fruits* (this has been removed in 1.2);
- base item (1046626) linked to custom group C:6944 has price of 0 and min customizations of 0 - this means buyer can checkout the base item for 0 price without any customizations?
- wherever base item has price 0, default selections or price range needs to be provided;
- item (1046626) for "Chicken Biryani" has veg=yes; how?
2. pls resubmit logs for group B including flow 4 & 5 as updated in the [test scenarios](https://docs.google.com/spreadsheets/d/1JZV6ZQzXcHUsOwegGtArX3DdIXYIy3gxkhQ00q7kICc/edit#gid=1367601795);

**Comment by BLR-0118** [comment]
@dgowda604

**Comment by dgowda604** [comment]
@BLR-0118 Updated v1.2 logs to reflect the inclusion of newly added test cases in the rollout plan
PR -> https://github.com/ONDC-Official/v1.2.0-logs/pull/119

**Comment by BLR-0118** [comment]
Flow 1
====
- search & on_search - use RET domain
- /on_search: item.descriptor.code (EAN) for F&B item (1046626) is wrong;
- display price handling for item 1046626 (with 0 price) not clear - either use item.price.tags.default_selection or item.price.tags.range;
- Base item & all customizations are 0 price - what does it mean?
1. CG:102160, CG:102161, 1046628);
2. CG:102162, CG:102163, CG:102164, 1046631;
- item.available.count - default value 99 means inventory available & 0 means out-of-stock; not clear what all the diff values used here mean?
- item.maximum.count - default value 99 means no cap per order; any other +ve value means cap per order; not clear what all the diff values used here mean?
- Incremental search:
1. Context.start_time, end_time should be in UTC, in the past;
2. Context.city should be *;
3, contact_details_consumer_care - not in correct format
4. item record - different from what's in full catalog refresh

Flow2
====
- /init & /on_init - billing.address.lat/lng, fulfillments.end.location.address.lat/lng are invalid;
- provider.locations missing in /on_select, /on_init (remove provider_location from on_init);
- /on_select - fulfillment.type required;

Flow 3
====
oos - error message (customization_group (C:7503) & customization (CG:111251) are switched

Flow 4
====
- reason code 012 triggers RTO; hence the proper /on_cancel flow as per contract reqd

Flow 5
====
- merchant cancel requires full /on_cancel flow as per contract (with quote trail, separate fulfillment for cancellation created)

**Comment by BLR-0118** [comment]
@dgowda604

**Comment by BLR-0118** [comment]
All issues mentioned above have to be fixed before logs can be reviewed. If there are issues with Pincode, pls raise with them to have it fixed. If they're not responding, pls let me know & I can talk to them.

**Comment by BLR-0118** [comment]
@dgowda604

**Comment by dgowda604** [comment]
@BLR-0118 as discussed submitted V1.2 logs along with RTO floe -> https://github.com/ONDC-Official/v1.2.0-logs/pull/137

**Comment by BLR-0118** [comment]
Flow 1
======
1. /on_search:
- store timings using the new construct should be cleanly defined (here multiple overlapping timings are defined which isn't correct) - my suggestion is to remove it for now & do it correctly in phase 2;
- incorrect definition:
base item price 0 for these items (1046626, 1046635) but customizations have > 0 price (correct):
in both cases, config for custom group & base item has "min" 0 (means minimum 0 customizations, i.e. no customizations mandatory); thus, buyer can checkout the base item itself for 0 price, which is incorrect;
- incorrect assignment of EAN code to item.descriptor.code for all F&B items;
- for different types of cakes, instead of using "non-veg", use "egg";

Flow 5
====
1. /rto_initiated:
- what does price.minimum_value for CG:109705 mean?

Pls only resubmit fixes for above;

**Comment by BLR-0118** [comment]
@dgowda604

**Comment by dgowda604** [comment]
@BLR-0118 resubmitted logs for FLOW1 & FLOW5 -> https://github.com/ONDC-Official/v1.2.0-logs/pull/140

**Comment by BLR-0118** [comment]
Why are you repeating the custom_group config inside the base item - custom_group config is defined under bpp/providers.categories and you can override it inside base item e.g. C:6944 - min / max of 1, input_type of select, seq of 1 is defined in bpp/providers.categories & repeated inside item. This increases size of payload;
Pls optimize this and include the custom_group config inside item only if it is being overridden; otherwise, the buyer app will just read from bpp/providers.categories;
Pls resubmit only this fix.

**Comment by BLR-0118** [comment]
@dgowda604

**Comment by dgowda604** [comment]
@BLR-0118 submitted on_search payload as per the comments -> https://github.com/ONDC-Official/v1.2.0-logs/pull/142

**Comment by BLR-0118** [comment]
logs cleared for F&B for 1.2 (phase 1)
