### ISSUE TITLE
ShopEG (SA) RSF - compliance check 

### ISSUE THREAD

**Issue by RupalSingla** [ONDC-Official/v1.2.0-logs#937]
on_settle:
message_id mismatched with on_settle API.
bap_id and bpp_id cannot have same values.

receiver_recon:
transaction_id missmatches with on_settle API.
receiver_recon happens after on_settle API , timestamp difference .

@BasanthVerma

**Comment by BasanthVerma** [comment]
@RupalSingla re-submitted the flows with fixes in context.bpp_id and bpp_uri for settle on_settle. 

We're a MSN, so we /settle to our merchants after we get /receiver_recon from buyer apps. 

Also this is tested using the mock server, all the transaction data is hardcoded and we're doing the best possible simulation using real preprod orders from the ONDC reference buyer app. 

Because the data is hardcoded in the yaml files of the mock server, in the `ShopEG/RSF - With local mock server/Flow 1 - success flow/on_receiver_recon.json` file, I missed updating the counterparty_recon_status values in the yaml file. It's 03 for 2 transactions, while it should be 01. The same transactions are re-used in Flow 2. Please ignore this.

**Comment by RupalSingla** [comment]
Receiver_recon

settlement_timestamp , timestamp for orderbook cretaion-created_at and updated_at cannot have same values
on_receiver_recon:

message.orderbook.orders.counterparty_recon_status or all the 5 orders are having different code values that are underpaid /overpaid/paid which is not possible ,it should be of one type

@BasanthVerma

**Comment by BasanthVerma** [comment]
receiver_recon - there is 1 day difference between created_at vs settlement_timestamp & updated_at in all the entries

on_receiver_recon - agreed, for success flow all must be 01. But In correction flow as per the test cases we're supposed to demonstrate 1 or more transactions which are underpaid/overpaid as well. Although both success and correction flow have 03, please see my previous comment or my explanation below as to why we both flows demonstrate correction logic.

The RSF endpoints were tested using the mock server. All data is hardcoded in the mock server for every log submission based on real orders in our database. We use real order Id and data that was placed on the reference buyer app and use mocked ids and timestamps related to reconciliation.
- In the first submission - success flow had counterparty_recon_status 01 for all 5 transactions, while 2 transactions had 03 in correction flow. 
- In the second submission - we missed to update all the counterparty_recon_status back to 01 to redo the flows.

Second submission was also made to show fixes in settle and on_settle which appears to be on hold now. 

@RupalSingla @sandeepshahi

**Comment by RupalSingla** [comment]
Logs cleared for version 1.0.0 @BasanthVerma
