### ISSUE TITLE
Channelier - LBNP - compliance check

### ISSUE THREAD

**Issue by abhinavv245** [ONDC-Official/v1.2.0-logs#984]
Multiple issues identified. Kindly use the [log verification tool](https://github.com/ONDC-Official/reference-implementations/tree/main/utilities/logistics-b2b/log-verification-utility) to test the logs and rectify the issues at your end before submitting. 

Kindly provide complete flows with search, on_search for each flow for a transaction. Tracking needs to be implemented. 

Also, please test with any other NP like MP2, shadowfax or Mahindra logistics as there are some issues with ref LSP app currently due to which the logs cannot be reviewed with it. 

@itsRajatkumar

**Comment by abhinavv245** [comment]
## All Flows

**/search**

- order prep time (provider.time.duration) is required for hyperlocal;

**/confirm**

- items/time (S2D TAT) should be provided
- average pickup time sent in /on_search may be sent (fulfillment.start.time.duration);
- PCC (start/instructions/short_desc) may be sent only when ready_to_ship is "yes";


**/on_status**

- quote/price/value should be a string (BAP should validate schema errors)

**/track**

- Message ID cannot be same as /confirm

@itsRajatkumar

**Comment by BLR-0118** [comment]
Flow 1
====
1. /search:
- order prep time (provider.time.duration) of 48 hrs is not correct for hyperlocal; LSPs use this to schedule their rider allocation algos, hence, pls use realistic values for this;

2. /init:
- payment.collected_by should be "BAP" (i.e. LBNP collects from SNP & pays LSP); this is the only logistics payment mode available today;

3. /confirm:
- if pickup code is of type OTP ("3"), pls use the fulfillment.start.authorization struct;

Flow 3
====
- pls share logs for cancellation by LBNP due to fulfillment TAT breach;

**Comment by BLR-0118** [comment]
@itsRajatkumar - pls fix the above & share logs for Flow 3 (cancellation by LBNP due to TAT breach);

**Comment by BLR-0118** [comment]
Flow 3
====
1. /search:
- order preparation time (provider.time.duration) needs to be provided for hyperlocal;

2. /confirm:
- /search has request for LSP with OTP authorization (at pickup) but pickup confirmation code used here is not OTP (type of "3" - other);
- for OTP to be used, the fulfillment.start (or end).authorization struct needs to be used (with time validity);

**Comment by BLR-0118** [comment]
@itsRajatkumar - clearing logs for v1.2.0 but pls make sure the above are fixed;
